apiVersion: snowflake.crossplane.io/v1alpha1
kind: Alert
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/alert
  labels:
    testing.upbound.io/example-name: alert
  name: alert
spec:
  forProvider:
    action: select 1 as c
    alertSchedule:
    - interval: 10
    comment: my alert
    condition: select 1 as c
    database: database
    enabled: true
    schema: schema
    warehouse: warehouse
