apiVersion: snowflake.crossplane.io/v1alpha1
kind: Listing
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/listing
  labels:
    testing.upbound.io/example-name: basic_inlined
  name: basic-inlined
spec:
  forProvider:
    manifest:
    - fromString: |
        title: title
        subtitle: subtitle
        description: description
        listing_terms:
          type: OFFLINE
