apiVersion: snowflake.crossplane.io/v1alpha1
kind: Pipe
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/pipe
  labels:
    testing.upbound.io/example-name: pipe
  name: pipe
spec:
  forProvider:
    autoIngest: false
    awsSnsTopicArn: '...'
    comment: A pipe.
    copyStatement: copy into ${snowflake_table.table.fully_qualified_name} from @${snowflake_stage.stage.fully_qualified_name}
    database: database_name
    schema: schema_name

---

apiVersion: snowflake.crossplane.io/v1alpha1
kind: Stage
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/pipe
  labels:
    testing.upbound.io/example-name: stage
  name: stage
spec:
  forProvider:
    database: ${snowflake_database.database.name}
    encryption: TYPE = 'NONE'
    schema: ${snowflake_schema.schema.name}
    storageIntegration: ${snowflake_storage_integration.storage_integration.name}
    url: s3://com.example.bucket/prefix
