apiVersion: snowflake.crossplane.io/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/table
  labels:
    testing.upbound.io/example-name: table
  name: table
spec:
  forProvider:
    changeTracking: false
    clusterBy:
    - to_date(DATE)
    column:
    - default:
      - sequence: ${snowflake_sequence.sequence.fully_qualified_name}
      name: id
      nullable: true
      type: int
    - identity:
      - startNum: 1
        stepNum: 3
      name: identity
      nullable: true
      type: NUMBER(38,0)
    - collate: en-ci
      name: data
      nullable: false
      type: text
    - name: DATE
      type: TIMESTAMP_NTZ(9)
    - comment: extra data
      name: extra
      type: VARIANT
    comment: A table.
    dataRetentionTimeInDays: ${snowflake_schema.schema.data_retention_time_in_days}
    database: database_name
    primaryKey:
    - keys:
      - data
      name: my_key
    schema: schema_name

---

apiVersion: snowflakeschema.crossplane.io/v1alpha1
kind: Schema
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/table
  labels:
    testing.upbound.io/example-name: schema
  name: schema
spec:
  forProvider:
    data_retention_days: 1
    database: database
    name: schema

---

apiVersion: snowflake.crossplane.io/v1alpha1
kind: Sequence
metadata:
  annotations:
    meta.upbound.io/example-id: snowflake/v1alpha1/table
  labels:
    testing.upbound.io/example-name: sequence
  name: sequence
spec:
  forProvider:
    database: database
    schema: schema
