apiVersion: snowflakefileformat.crossplane.io/v1alpha1
kind: Format
metadata:
  name: example-file-format
spec:
  forProvider:
    name: ff_file_format
    database: CROSS_DB
    formatType: CSV
    schema: UPJET