apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-snowflake-volvocars
spec:
  package: ghcr.io/kpatange/provider-snowflake-volvocars:v0.0.3
  packagePullSecrets:
    - name: ghcr-secret