apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "organization_name": "DOYVEHH",
      "account_name": "BP45687",
      "user": "kpatange",
      "password": "8St2B519xaFVLFugU8IItm0"
    }