// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthenticationPolicyAttachmentInitParameters struct {

	// (String) Fully qualified name of the authentication policy
	// Fully qualified name of the authentication policy
	AuthenticationPolicyName *string `json:"authenticationPolicyName,omitempty" tf:"authentication_policy_name,omitempty"`

	// (String) User name of the user you want to attach the authentication policy to
	// User name of the user you want to attach the authentication policy to
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type AuthenticationPolicyAttachmentObservation struct {

	// (String) Fully qualified name of the authentication policy
	// Fully qualified name of the authentication policy
	AuthenticationPolicyName *string `json:"authenticationPolicyName,omitempty" tf:"authentication_policy_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) User name of the user you want to attach the authentication policy to
	// User name of the user you want to attach the authentication policy to
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type AuthenticationPolicyAttachmentParameters struct {

	// (String) Fully qualified name of the authentication policy
	// Fully qualified name of the authentication policy
	// +kubebuilder:validation:Optional
	AuthenticationPolicyName *string `json:"authenticationPolicyName,omitempty" tf:"authentication_policy_name,omitempty"`

	// (String) User name of the user you want to attach the authentication policy to
	// User name of the user you want to attach the authentication policy to
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

// AuthenticationPolicyAttachmentSpec defines the desired state of AuthenticationPolicyAttachment
type AuthenticationPolicyAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthenticationPolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthenticationPolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// AuthenticationPolicyAttachmentStatus defines the observed state of AuthenticationPolicyAttachment.
type AuthenticationPolicyAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthenticationPolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AuthenticationPolicyAttachment is the Schema for the AuthenticationPolicyAttachments API. Specifies the authentication policy to use for a certain user.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type AuthenticationPolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.authenticationPolicyName) || (has(self.initProvider) && has(self.initProvider.authenticationPolicyName))",message="spec.forProvider.authenticationPolicyName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userName) || (has(self.initProvider) && has(self.initProvider.userName))",message="spec.forProvider.userName is a required parameter"
	Spec   AuthenticationPolicyAttachmentSpec   `json:"spec"`
	Status AuthenticationPolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthenticationPolicyAttachmentList contains a list of AuthenticationPolicyAttachments
type AuthenticationPolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthenticationPolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	AuthenticationPolicyAttachment_Kind             = "AuthenticationPolicyAttachment"
	AuthenticationPolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthenticationPolicyAttachment_Kind}.String()
	AuthenticationPolicyAttachment_KindAPIVersion   = AuthenticationPolicyAttachment_Kind + "." + CRDGroupVersion.String()
	AuthenticationPolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(AuthenticationPolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthenticationPolicyAttachment{}, &AuthenticationPolicyAttachmentList{})
}
