// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PasswordPolicyAttachmentInitParameters struct {

	// (String) Fully qualified name of the password policy
	// Fully qualified name of the password policy
	PasswordPolicyName *string `json:"passwordPolicyName,omitempty" tf:"password_policy_name,omitempty"`

	// (String) User name of the user you want to attach the password policy to
	// User name of the user you want to attach the password policy to
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type PasswordPolicyAttachmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Fully qualified name of the password policy
	// Fully qualified name of the password policy
	PasswordPolicyName *string `json:"passwordPolicyName,omitempty" tf:"password_policy_name,omitempty"`

	// (String) User name of the user you want to attach the password policy to
	// User name of the user you want to attach the password policy to
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type PasswordPolicyAttachmentParameters struct {

	// (String) Fully qualified name of the password policy
	// Fully qualified name of the password policy
	// +kubebuilder:validation:Optional
	PasswordPolicyName *string `json:"passwordPolicyName,omitempty" tf:"password_policy_name,omitempty"`

	// (String) User name of the user you want to attach the password policy to
	// User name of the user you want to attach the password policy to
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

// PasswordPolicyAttachmentSpec defines the desired state of PasswordPolicyAttachment
type PasswordPolicyAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PasswordPolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PasswordPolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// PasswordPolicyAttachmentStatus defines the observed state of PasswordPolicyAttachment.
type PasswordPolicyAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PasswordPolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PasswordPolicyAttachment is the Schema for the PasswordPolicyAttachments API. Specifies the password policy to use for a certain user.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type PasswordPolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.passwordPolicyName) || (has(self.initProvider) && has(self.initProvider.passwordPolicyName))",message="spec.forProvider.passwordPolicyName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userName) || (has(self.initProvider) && has(self.initProvider.userName))",message="spec.forProvider.userName is a required parameter"
	Spec   PasswordPolicyAttachmentSpec   `json:"spec"`
	Status PasswordPolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PasswordPolicyAttachmentList contains a list of PasswordPolicyAttachments
type PasswordPolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PasswordPolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	PasswordPolicyAttachment_Kind             = "PasswordPolicyAttachment"
	PasswordPolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PasswordPolicyAttachment_Kind}.String()
	PasswordPolicyAttachment_KindAPIVersion   = PasswordPolicyAttachment_Kind + "." + CRDGroupVersion.String()
	PasswordPolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(PasswordPolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&PasswordPolicyAttachment{}, &PasswordPolicyAttachmentList{})
}
