apiVersion: failover.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: failover/v1alpha1/group
  labels:
    testing.upbound.io/example-name: source_failover_group
  name: source-failover-group
spec:
  forProvider:
    allowedAccounts:
    - <org_name>.<target_account_name1>
    - <org_name>.<target_account_name2>
    allowedDatabases:
    - ${snowflake_database.db.name}
    allowedIntegrationTypes:
    - SECURITY INTEGRATIONS
    objectTypes:
    - WAREHOUSES
    - DATABASES
    - INTEGRATIONS
    - ROLES
    replicationSchedule:
    - cron:
      - expression: 0 0 10-20 * TUE,THU
        timeZone: UTC

---

apiVersion: snowflakedatabase.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    meta.upbound.io/example-id: failover/v1alpha1/group
  labels:
    testing.upbound.io/example-name: db
  name: db
spec:
  forProvider:
    name: db1
