// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IntegrationInitParameters struct {

	// (List of String) Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service endpoints and resources within those proxies.
	// Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service endpoints and resources within those proxies.
	APIAllowedPrefixes []*string `json:"apiAllowedPrefixes,omitempty" tf:"api_allowed_prefixes,omitempty"`

	// (String) (Default: “) ARN of a cloud platform role.
	// (Default: “) ARN of a cloud platform role.
	APIAwsRoleArn *string `json:"apiAwsRoleArn,omitempty" tf:"api_aws_role_arn,omitempty"`

	// (List of String) Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	APIBlockedPrefixes []*string `json:"apiBlockedPrefixes,omitempty" tf:"api_blocked_prefixes,omitempty"`

	// (String) The service account used for communication with the Google API Gateway.
	// The service account used for communication with the Google API Gateway.
	APIGCPServiceAccount *string `json:"apiGcpServiceAccount,omitempty" tf:"api_gcp_service_account,omitempty"`

	// (String, Sensitive) The API key (also called a “subscription key”).
	// The API key (also called a “subscription key”).
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String) Specifies the HTTPS proxy service type.
	// Specifies the HTTPS proxy service type.
	APIProvider *string `json:"apiProvider,omitempty" tf:"api_provider,omitempty"`

	// (String) (Default: “) The 'Application (client) id' of the Azure AD app for your remote service.
	// (Default: “) The 'Application (client) id' of the Azure AD app for your remote service.
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String) (Default: “) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// (Default: “) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) (Default: true) Specifies whether this API integration is enabled or disabled. If the API integration is disabled, any external function that relies on it will not work.
	// (Default: `true`) Specifies whether this API integration is enabled or disabled. If the API integration is disabled, any external function that relies on it will not work.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) (Default: “) The audience claim when generating the JWT (JSON Web Token) to authenticate to the Google API Gateway.
	// (Default: “) The audience claim when generating the JWT (JSON Web Token) to authenticate to the Google API Gateway.
	GoogleAudience *string `json:"googleAudience,omitempty" tf:"google_audience,omitempty"`
}

type IntegrationObservation struct {

	// (List of String) Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service endpoints and resources within those proxies.
	// Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service endpoints and resources within those proxies.
	APIAllowedPrefixes []*string `json:"apiAllowedPrefixes,omitempty" tf:"api_allowed_prefixes,omitempty"`

	// (String) The external ID that Snowflake will use when assuming the AWS role.
	// The external ID that Snowflake will use when assuming the AWS role.
	APIAwsExternalID *string `json:"apiAwsExternalId,omitempty" tf:"api_aws_external_id,omitempty"`

	// (String) The Snowflake user that will attempt to assume the AWS role.
	// The Snowflake user that will attempt to assume the AWS role.
	APIAwsIAMUserArn *string `json:"apiAwsIamUserArn,omitempty" tf:"api_aws_iam_user_arn,omitempty"`

	// (String) (Default: “) ARN of a cloud platform role.
	// (Default: “) ARN of a cloud platform role.
	APIAwsRoleArn *string `json:"apiAwsRoleArn,omitempty" tf:"api_aws_role_arn,omitempty"`

	// (List of String) Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	APIBlockedPrefixes []*string `json:"apiBlockedPrefixes,omitempty" tf:"api_blocked_prefixes,omitempty"`

	// (String) The service account used for communication with the Google API Gateway.
	// The service account used for communication with the Google API Gateway.
	APIGCPServiceAccount *string `json:"apiGcpServiceAccount,omitempty" tf:"api_gcp_service_account,omitempty"`

	// (String) Specifies the HTTPS proxy service type.
	// Specifies the HTTPS proxy service type.
	APIProvider *string `json:"apiProvider,omitempty" tf:"api_provider,omitempty"`

	// (String) (Default: “) The 'Application (client) id' of the Azure AD app for your remote service.
	// (Default: “) The 'Application (client) id' of the Azure AD app for your remote service.
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String)
	AzureConsentURL *string `json:"azureConsentUrl,omitempty" tf:"azure_consent_url,omitempty"`

	// (String)
	AzureMultiTenantAppName *string `json:"azureMultiTenantAppName,omitempty" tf:"azure_multi_tenant_app_name,omitempty"`

	// (String) (Default: “) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// (Default: “) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (String)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Date and time when the API integration was created.
	// Date and time when the API integration was created.
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Boolean) (Default: true) Specifies whether this API integration is enabled or disabled. If the API integration is disabled, any external function that relies on it will not work.
	// (Default: `true`) Specifies whether this API integration is enabled or disabled. If the API integration is disabled, any external function that relies on it will not work.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) (Default: “) The audience claim when generating the JWT (JSON Web Token) to authenticate to the Google API Gateway.
	// (Default: “) The audience claim when generating the JWT (JSON Web Token) to authenticate to the Google API Gateway.
	GoogleAudience *string `json:"googleAudience,omitempty" tf:"google_audience,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type IntegrationParameters struct {

	// (List of String) Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service endpoints and resources within those proxies.
	// Explicitly limits external functions that use the integration to reference one or more HTTPS proxy service endpoints and resources within those proxies.
	// +kubebuilder:validation:Optional
	APIAllowedPrefixes []*string `json:"apiAllowedPrefixes,omitempty" tf:"api_allowed_prefixes,omitempty"`

	// (String) (Default: “) ARN of a cloud platform role.
	// (Default: “) ARN of a cloud platform role.
	// +kubebuilder:validation:Optional
	APIAwsRoleArn *string `json:"apiAwsRoleArn,omitempty" tf:"api_aws_role_arn,omitempty"`

	// (List of String) Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// Lists the endpoints and resources in the HTTPS proxy service that are not allowed to be called from Snowflake.
	// +kubebuilder:validation:Optional
	APIBlockedPrefixes []*string `json:"apiBlockedPrefixes,omitempty" tf:"api_blocked_prefixes,omitempty"`

	// (String) The service account used for communication with the Google API Gateway.
	// The service account used for communication with the Google API Gateway.
	// +kubebuilder:validation:Optional
	APIGCPServiceAccount *string `json:"apiGcpServiceAccount,omitempty" tf:"api_gcp_service_account,omitempty"`

	// (String, Sensitive) The API key (also called a “subscription key”).
	// The API key (also called a “subscription key”).
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v1.SecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String) Specifies the HTTPS proxy service type.
	// Specifies the HTTPS proxy service type.
	// +kubebuilder:validation:Optional
	APIProvider *string `json:"apiProvider,omitempty" tf:"api_provider,omitempty"`

	// (String) (Default: “) The 'Application (client) id' of the Azure AD app for your remote service.
	// (Default: “) The 'Application (client) id' of the Azure AD app for your remote service.
	// +kubebuilder:validation:Optional
	AzureAdApplicationID *string `json:"azureAdApplicationId,omitempty" tf:"azure_ad_application_id,omitempty"`

	// (String) (Default: “) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// (Default: “) Specifies the ID for your Office 365 tenant that all Azure API Management instances belong to.
	// +kubebuilder:validation:Optional
	AzureTenantID *string `json:"azureTenantId,omitempty" tf:"azure_tenant_id,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) (Default: true) Specifies whether this API integration is enabled or disabled. If the API integration is disabled, any external function that relies on it will not work.
	// (Default: `true`) Specifies whether this API integration is enabled or disabled. If the API integration is disabled, any external function that relies on it will not work.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) (Default: “) The audience claim when generating the JWT (JSON Web Token) to authenticate to the Google API Gateway.
	// (Default: “) The audience claim when generating the JWT (JSON Web Token) to authenticate to the Google API Gateway.
	// +kubebuilder:validation:Optional
	GoogleAudience *string `json:"googleAudience,omitempty" tf:"google_audience,omitempty"`
}

// IntegrationSpec defines the desired state of Integration
type IntegrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IntegrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IntegrationInitParameters `json:"initProvider,omitempty"`
}

// IntegrationStatus defines the observed state of Integration.
type IntegrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Integration is the Schema for the Integrations API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Integration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiAllowedPrefixes) || (has(self.initProvider) && has(self.initProvider.apiAllowedPrefixes))",message="spec.forProvider.apiAllowedPrefixes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiProvider) || (has(self.initProvider) && has(self.initProvider.apiProvider))",message="spec.forProvider.apiProvider is a required parameter"
	Spec   IntegrationSpec   `json:"spec"`
	Status IntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntegrationList contains a list of Integrations
type IntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Integration `json:"items"`
}

// Repository type metadata.
var (
	Integration_Kind             = "Integration"
	Integration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Integration_Kind}.String()
	Integration_KindAPIVersion   = Integration_Kind + "." + CRDGroupVersion.String()
	Integration_GroupVersionKind = CRDGroupVersion.WithKind(Integration_Kind)
)

func init() {
	SchemeBuilder.Register(&Integration{}, &IntegrationList{})
}
