apiVersion: snowflakeuser.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakeuser/v1alpha1/user
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal2
spec:
  forProvider:
    name: mike
    passwordSecretRef:
      key: password
      name: snowflake-creds
      namespace: crossplane-system