// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ScalaArgumentsInitParameters struct {

	// (String) The argument type.
	// The argument type.
	ArgDataType *string `json:"argDataType,omitempty" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the function definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the function definition.
	ArgName *string `json:"argName,omitempty" tf:"arg_name,omitempty"`
}

type ScalaArgumentsObservation struct {

	// (String) The argument type.
	// The argument type.
	ArgDataType *string `json:"argDataType,omitempty" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the function definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the function definition.
	ArgName *string `json:"argName,omitempty" tf:"arg_name,omitempty"`
}

type ScalaArgumentsParameters struct {

	// (String) The argument type.
	// The argument type.
	// +kubebuilder:validation:Optional
	ArgDataType *string `json:"argDataType" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	// +kubebuilder:validation:Optional
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the function definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the function definition.
	// +kubebuilder:validation:Optional
	ArgName *string `json:"argName" tf:"arg_name,omitempty"`
}

type ScalaImportsInitParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type ScalaImportsObservation struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type ScalaImportsParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	// +kubebuilder:validation:Optional
	PathOnStage *string `json:"pathOnStage" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	// +kubebuilder:validation:Optional
	StageLocation *string `json:"stageLocation" tf:"stage_location,omitempty"`
}

type ScalaInitParameters struct {

	// (Block List) List of the arguments for the function. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the function. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#all-languages) for more details.
	Arguments []ScalaArgumentsInitParameters `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined function) Specifies a comment for the function.
	// (Default: `user-defined function`) Specifies a comment for the function.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the function. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the function. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this function’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// The names of [external access integrations](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) needed in order for this function’s handler code to access external networks. An external access integration specifies [network rules](https://docs.snowflake.com/en/sql-reference/sql/create-network-rule) and [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (String) Defines the handler code executed when the UDF is called. Wrapping $$ signs are added by the provider automatically; do not include them. The function_definition value must be Scala source code. For more information, see Introduction to Scala UDFs. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the handler code executed when the UDF is called. Wrapping `$$` signs are added by the provider automatically; do not include them. The `function_definition` value must be Scala source code. For more information, see [Introduction to Scala UDFs](https://docs.snowflake.com/en/developer-guide/udf/scala/udf-scala-introduction). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	FunctionDefinition *string `json:"functionDefinition,omitempty" tf:"function_definition,omitempty"`

	// tabular value, the HANDLER value should be a method name, as in the following form: MyClass.myMethod.
	// The name of the handler method or class. If the handler is for a scalar UDF, returning a non-tabular value, the HANDLER value should be a method name, as in the following form: `MyClass.myMethod`.
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// JAR file might a file read by handler code. For an example, see Reading a file specified statically in IMPORTS. Consult the docs. (see below for nested schema)
	// The location (stage), path, and name of the file(s) to import, such as a JAR or other kind of file. The JAR file might contain handler dependency libraries. It can contain one or more .class files and zero or more resource files. JNI (Java Native Interface) is not supported. Snowflake prohibits loading libraries that contain native code (as opposed to Java bytecode). A non-JAR file might a file read by handler code. For an example, see [Reading a file specified statically in IMPORTS](https://docs.snowflake.com/en/developer-guide/udf/java/udf-java-cookbook.html#label-reading-file-from-java-udf-imports). Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#scala).
	Imports []ScalaImportsInitParameters `json:"imports,omitempty" tf:"imports,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the function is secure. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the function is secure. By design, the Snowflake's `SHOW FUNCTIONS` command does not provide information about secure functions (consult [function docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#id1) and [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the function when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (Set of String) The name and version number of Snowflake system packages required as dependencies. The value should be of the form package_name:version_number, where package_name is snowflake_domain:package.
	// The name and version number of Snowflake system packages required as dependencies. The value should be of the form `package_name:version_number`, where `package_name` is `snowflake_domain:package`.
	// +listType=set
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// insensitive): VOLATILE | IMMUTABLE.
	// Specifies the behavior of the function when returning results. Valid values are (case-insensitive): `VOLATILE` | `IMMUTABLE`.
	ReturnResultsBehavior *string `json:"returnResultsBehavior,omitempty" tf:"return_results_behavior,omitempty"`

	// (String) Specifies the results returned by the UDF, which determines the UDF type. Use <result_data_type> to create a scalar UDF that returns a single value with the specified data type. Use TABLE (col_name col_data_type, ...) to creates a table UDF that returns tabular results with the specified table column(s) and column type(s). For the details, consult the docs.
	// Specifies the results returned by the UDF, which determines the UDF type. Use `<result_data_type>` to create a scalar UDF that returns a single value with the specified data type. Use `TABLE (col_name col_data_type, ...)` to creates a table UDF that returns tabular results with the specified table column(s) and column type(s). For the details, consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#all-languages).
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) Specifies the Scala runtime version to use. The supported versions of Scala are: 2.12.
	// Specifies the Scala runtime version to use. The supported versions of Scala are: 2.12.
	RuntimeVersion *string `json:"runtimeVersion,omitempty" tf:"runtime_version,omitempty"`

	// (String) The schema in which to create the function. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the function. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	// Assigns the names of [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the [external access integration](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter.
	Secrets []ScalaSecretsInitParameters `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// tabular value, the HANDLER value should be a method name, as in the following form: MyClass.myMethod. (see below for nested schema)
	// The name of the handler method or class. If the handler is for a scalar UDF, returning a non-tabular value, the HANDLER value should be a method name, as in the following form: `MyClass.myMethod`.
	TargetPath []ScalaTargetPathInitParameters `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ScalaObservation struct {

	// (Block List) List of the arguments for the function. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the function. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#all-languages) for more details.
	Arguments []ScalaArgumentsObservation `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined function) Specifies a comment for the function.
	// (Default: `user-defined function`) Specifies a comment for the function.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the function. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the function. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this function’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// The names of [external access integrations](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) needed in order for this function’s handler code to access external networks. An external access integration specifies [network rules](https://docs.snowflake.com/en/sql-reference/sql/create-network-rule) and [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) Defines the handler code executed when the UDF is called. Wrapping $$ signs are added by the provider automatically; do not include them. The function_definition value must be Scala source code. For more information, see Introduction to Scala UDFs. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the handler code executed when the UDF is called. Wrapping `$$` signs are added by the provider automatically; do not include them. The `function_definition` value must be Scala source code. For more information, see [Introduction to Scala UDFs](https://docs.snowflake.com/en/developer-guide/udf/scala/udf-scala-introduction). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	FunctionDefinition *string `json:"functionDefinition,omitempty" tf:"function_definition,omitempty"`

	// (String) Specifies language for the user. Used to detect external changes.
	// Specifies language for the user. Used to detect external changes.
	FunctionLanguage *string `json:"functionLanguage,omitempty" tf:"function_language,omitempty"`

	// tabular value, the HANDLER value should be a method name, as in the following form: MyClass.myMethod.
	// The name of the handler method or class. If the handler is for a scalar UDF, returning a non-tabular value, the HANDLER value should be a method name, as in the following form: `MyClass.myMethod`.
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// JAR file might a file read by handler code. For an example, see Reading a file specified statically in IMPORTS. Consult the docs. (see below for nested schema)
	// The location (stage), path, and name of the file(s) to import, such as a JAR or other kind of file. The JAR file might contain handler dependency libraries. It can contain one or more .class files and zero or more resource files. JNI (Java Native Interface) is not supported. Snowflake prohibits loading libraries that contain native code (as opposed to Java bytecode). A non-JAR file might a file read by handler code. For an example, see [Reading a file specified statically in IMPORTS](https://docs.snowflake.com/en/developer-guide/udf/java/udf-java-cookbook.html#label-reading-file-from-java-udf-imports). Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#scala).
	Imports []ScalaImportsObservation `json:"imports,omitempty" tf:"imports,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the function is secure. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the function is secure. By design, the Snowflake's `SHOW FUNCTIONS` command does not provide information about secure functions (consult [function docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#id1) and [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the function when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (Set of String) The name and version number of Snowflake system packages required as dependencies. The value should be of the form package_name:version_number, where package_name is snowflake_domain:package.
	// The name and version number of Snowflake system packages required as dependencies. The value should be of the form `package_name:version_number`, where `package_name` is `snowflake_domain:package`.
	// +listType=set
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// (List of Object) Outputs the result of SHOW PARAMETERS IN FUNCTION for the given function. (see below for nested schema)
	// Outputs the result of `SHOW PARAMETERS IN FUNCTION` for the given function.
	Parameters []ScalaParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// insensitive): VOLATILE | IMMUTABLE.
	// Specifies the behavior of the function when returning results. Valid values are (case-insensitive): `VOLATILE` | `IMMUTABLE`.
	ReturnResultsBehavior *string `json:"returnResultsBehavior,omitempty" tf:"return_results_behavior,omitempty"`

	// (String) Specifies the results returned by the UDF, which determines the UDF type. Use <result_data_type> to create a scalar UDF that returns a single value with the specified data type. Use TABLE (col_name col_data_type, ...) to creates a table UDF that returns tabular results with the specified table column(s) and column type(s). For the details, consult the docs.
	// Specifies the results returned by the UDF, which determines the UDF type. Use `<result_data_type>` to create a scalar UDF that returns a single value with the specified data type. Use `TABLE (col_name col_data_type, ...)` to creates a table UDF that returns tabular results with the specified table column(s) and column type(s). For the details, consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#all-languages).
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) Specifies the Scala runtime version to use. The supported versions of Scala are: 2.12.
	// Specifies the Scala runtime version to use. The supported versions of Scala are: 2.12.
	RuntimeVersion *string `json:"runtimeVersion,omitempty" tf:"runtime_version,omitempty"`

	// (String) The schema in which to create the function. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the function. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	// Assigns the names of [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the [external access integration](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter.
	Secrets []ScalaSecretsObservation `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (List of Object) Outputs the result of SHOW FUNCTION for the given function. (see below for nested schema)
	// Outputs the result of `SHOW FUNCTION` for the given function.
	ShowOutput []ScalaShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// tabular value, the HANDLER value should be a method name, as in the following form: MyClass.myMethod. (see below for nested schema)
	// The name of the handler method or class. If the handler is for a scalar UDF, returning a non-tabular value, the HANDLER value should be a method name, as in the following form: `MyClass.myMethod`.
	TargetPath []ScalaTargetPathObservation `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ScalaParameters struct {

	// (Block List) List of the arguments for the function. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the function. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#all-languages) for more details.
	// +kubebuilder:validation:Optional
	Arguments []ScalaArgumentsParameters `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined function) Specifies a comment for the function.
	// (Default: `user-defined function`) Specifies a comment for the function.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the function. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the function. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	// +kubebuilder:validation:Optional
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this function’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// The names of [external access integrations](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) needed in order for this function’s handler code to access external networks. An external access integration specifies [network rules](https://docs.snowflake.com/en/sql-reference/sql/create-network-rule) and [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// +kubebuilder:validation:Optional
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (String) Defines the handler code executed when the UDF is called. Wrapping $$ signs are added by the provider automatically; do not include them. The function_definition value must be Scala source code. For more information, see Introduction to Scala UDFs. To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the handler code executed when the UDF is called. Wrapping `$$` signs are added by the provider automatically; do not include them. The `function_definition` value must be Scala source code. For more information, see [Introduction to Scala UDFs](https://docs.snowflake.com/en/developer-guide/udf/scala/udf-scala-introduction). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// +kubebuilder:validation:Optional
	FunctionDefinition *string `json:"functionDefinition,omitempty" tf:"function_definition,omitempty"`

	// tabular value, the HANDLER value should be a method name, as in the following form: MyClass.myMethod.
	// The name of the handler method or class. If the handler is for a scalar UDF, returning a non-tabular value, the HANDLER value should be a method name, as in the following form: `MyClass.myMethod`.
	// +kubebuilder:validation:Optional
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// JAR file might a file read by handler code. For an example, see Reading a file specified statically in IMPORTS. Consult the docs. (see below for nested schema)
	// The location (stage), path, and name of the file(s) to import, such as a JAR or other kind of file. The JAR file might contain handler dependency libraries. It can contain one or more .class files and zero or more resource files. JNI (Java Native Interface) is not supported. Snowflake prohibits loading libraries that contain native code (as opposed to Java bytecode). A non-JAR file might a file read by handler code. For an example, see [Reading a file specified statically in IMPORTS](https://docs.snowflake.com/en/developer-guide/udf/java/udf-java-cookbook.html#label-reading-file-from-java-udf-imports). Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#scala).
	// +kubebuilder:validation:Optional
	Imports []ScalaImportsParameters `json:"imports,omitempty" tf:"imports,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the function is secure. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the function is secure. By design, the Snowflake's `SHOW FUNCTIONS` command does not provide information about secure functions (consult [function docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#id1) and [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	// +kubebuilder:validation:Optional
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	// +kubebuilder:validation:Optional
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the function when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	// +kubebuilder:validation:Optional
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (Set of String) The name and version number of Snowflake system packages required as dependencies. The value should be of the form package_name:version_number, where package_name is snowflake_domain:package.
	// The name and version number of Snowflake system packages required as dependencies. The value should be of the form `package_name:version_number`, where `package_name` is `snowflake_domain:package`.
	// +kubebuilder:validation:Optional
	// +listType=set
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// insensitive): VOLATILE | IMMUTABLE.
	// Specifies the behavior of the function when returning results. Valid values are (case-insensitive): `VOLATILE` | `IMMUTABLE`.
	// +kubebuilder:validation:Optional
	ReturnResultsBehavior *string `json:"returnResultsBehavior,omitempty" tf:"return_results_behavior,omitempty"`

	// (String) Specifies the results returned by the UDF, which determines the UDF type. Use <result_data_type> to create a scalar UDF that returns a single value with the specified data type. Use TABLE (col_name col_data_type, ...) to creates a table UDF that returns tabular results with the specified table column(s) and column type(s). For the details, consult the docs.
	// Specifies the results returned by the UDF, which determines the UDF type. Use `<result_data_type>` to create a scalar UDF that returns a single value with the specified data type. Use `TABLE (col_name col_data_type, ...)` to creates a table UDF that returns tabular results with the specified table column(s) and column type(s). For the details, consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-function#all-languages).
	// +kubebuilder:validation:Optional
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) Specifies the Scala runtime version to use. The supported versions of Scala are: 2.12.
	// Specifies the Scala runtime version to use. The supported versions of Scala are: 2.12.
	// +kubebuilder:validation:Optional
	RuntimeVersion *string `json:"runtimeVersion,omitempty" tf:"runtime_version,omitempty"`

	// (String) The schema in which to create the function. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the function. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	// Assigns the names of [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the [external access integration](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// +kubebuilder:validation:Optional
	Secrets []ScalaSecretsParameters `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// tabular value, the HANDLER value should be a method name, as in the following form: MyClass.myMethod. (see below for nested schema)
	// The name of the handler method or class. If the handler is for a scalar UDF, returning a non-tabular value, the HANDLER value should be a method name, as in the following form: `MyClass.myMethod`.
	// +kubebuilder:validation:Optional
	TargetPath []ScalaTargetPathParameters `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	// +kubebuilder:validation:Optional
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ScalaParametersEnableConsoleOutputInitParameters struct {
}

type ScalaParametersEnableConsoleOutputObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ScalaParametersEnableConsoleOutputParameters struct {
}

type ScalaParametersInitParameters struct {
}

type ScalaParametersLogLevelInitParameters struct {
}

type ScalaParametersLogLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ScalaParametersLogLevelParameters struct {
}

type ScalaParametersMetricLevelInitParameters struct {
}

type ScalaParametersMetricLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ScalaParametersMetricLevelParameters struct {
}

type ScalaParametersObservation struct {

	// (Boolean) Enable stdout/stderr fast path logging for anonymous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	EnableConsoleOutput []ScalaParametersEnableConsoleOutputObservation `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	LogLevel []ScalaParametersLogLevelObservation `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	MetricLevel []ScalaParametersMetricLevelObservation `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	TraceLevel []ScalaParametersTraceLevelObservation `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ScalaParametersParameters struct {
}

type ScalaParametersTraceLevelInitParameters struct {
}

type ScalaParametersTraceLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ScalaParametersTraceLevelParameters struct {
}

type ScalaSecretsInitParameters struct {

	// (String) Fully qualified name of the allowed secret. You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// Fully qualified name of the allowed [secret](https://docs.snowflake.com/en/sql-reference/sql/create-secret). You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The variable that will be used in handler code when retrieving information from the secret.
	// The variable that will be used in handler code when retrieving information from the secret.
	SecretVariableName *string `json:"secretVariableName,omitempty" tf:"secret_variable_name,omitempty"`
}

type ScalaSecretsObservation struct {

	// (String) Fully qualified name of the allowed secret. You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// Fully qualified name of the allowed [secret](https://docs.snowflake.com/en/sql-reference/sql/create-secret). You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The variable that will be used in handler code when retrieving information from the secret.
	// The variable that will be used in handler code when retrieving information from the secret.
	SecretVariableName *string `json:"secretVariableName,omitempty" tf:"secret_variable_name,omitempty"`
}

type ScalaSecretsParameters struct {

	// (String) Fully qualified name of the allowed secret. You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// Fully qualified name of the allowed [secret](https://docs.snowflake.com/en/sql-reference/sql/create-secret). You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId" tf:"secret_id,omitempty"`

	// (String) The variable that will be used in handler code when retrieving information from the secret.
	// The variable that will be used in handler code when retrieving information from the secret.
	// +kubebuilder:validation:Optional
	SecretVariableName *string `json:"secretVariableName" tf:"secret_variable_name,omitempty"`
}

type ScalaShowOutputInitParameters struct {
}

type ScalaShowOutputObservation struct {

	// (String)
	ArgumentsRaw *string `json:"argumentsRaw,omitempty" tf:"arguments_raw,omitempty"`

	// (String)
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this function’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	ExternalAccessIntegrations *string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Boolean)
	IsAggregate *bool `json:"isAggregate,omitempty" tf:"is_aggregate,omitempty"`

	// (Boolean)
	IsAnsi *bool `json:"isAnsi,omitempty" tf:"is_ansi,omitempty"`

	// (Boolean)
	IsBuiltin *bool `json:"isBuiltin,omitempty" tf:"is_builtin,omitempty"`

	// (Boolean)
	IsDataMetric *bool `json:"isDataMetric,omitempty" tf:"is_data_metric,omitempty"`

	// (Boolean)
	IsExternalFunction *bool `json:"isExternalFunction,omitempty" tf:"is_external_function,omitempty"`

	// (Boolean)
	IsMemoizable *bool `json:"isMemoizable,omitempty" tf:"is_memoizable,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the function is secure. Use the role owning the function while managing secure functions. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *bool `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (Boolean)
	IsTableFunction *bool `json:"isTableFunction,omitempty" tf:"is_table_function,omitempty"`

	// (String)
	Language *string `json:"language,omitempty" tf:"language,omitempty"`

	// (Number)
	MaxNumArguments *float64 `json:"maxNumArguments,omitempty" tf:"max_num_arguments,omitempty"`

	// (Number)
	MinNumArguments *float64 `json:"minNumArguments,omitempty" tf:"min_num_arguments,omitempty"`

	// (String) The name of the function; the identifier does not need to be unique for the schema in which the function is created because UDFs are identified and resolved by the combination of the name and argument types. Check the docs. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (Boolean)
	ValidForClustering *bool `json:"validForClustering,omitempty" tf:"valid_for_clustering,omitempty"`
}

type ScalaShowOutputParameters struct {
}

type ScalaTargetPathInitParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type ScalaTargetPathObservation struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type ScalaTargetPathParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	// +kubebuilder:validation:Optional
	PathOnStage *string `json:"pathOnStage" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	// +kubebuilder:validation:Optional
	StageLocation *string `json:"stageLocation" tf:"stage_location,omitempty"`
}

// ScalaSpec defines the desired state of Scala
type ScalaSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScalaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScalaInitParameters `json:"initProvider,omitempty"`
}

// ScalaStatus defines the observed state of Scala.
type ScalaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScalaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Scala is the Schema for the Scalas API. Resource used to manage scala function objects. For more information, check function documentation https://docs.snowflake.com/en/sql-reference/sql/create-function.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Scala struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.handler) || (has(self.initProvider) && has(self.initProvider.handler))",message="spec.forProvider.handler is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.returnType) || (has(self.initProvider) && has(self.initProvider.returnType))",message="spec.forProvider.returnType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runtimeVersion) || (has(self.initProvider) && has(self.initProvider.runtimeVersion))",message="spec.forProvider.runtimeVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	Spec   ScalaSpec   `json:"spec"`
	Status ScalaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScalaList contains a list of Scalas
type ScalaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Scala `json:"items"`
}

// Repository type metadata.
var (
	Scala_Kind             = "Scala"
	Scala_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Scala_Kind}.String()
	Scala_KindAPIVersion   = Scala_Kind + "." + CRDGroupVersion.String()
	Scala_GroupVersionKind = CRDGroupVersion.WithKind(Scala_Kind)
)

func init() {
	SchemeBuilder.Register(&Scala{}, &ScalaList{})
}
