// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DescribeOutputInitParameters struct {
}

type DescribeOutputObservation struct {

	// (String) Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	APIIntegration *string `json:"apiIntegration,omitempty" tf:"api_integration,omitempty"`

	// (String) Specifies a comment for the git repository.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String) Specifies the Snowflake secret fully qualified name (e.g "\"<db_name>\".\"<schema_name>\".\"<secret_name>\"") containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	GitCredentials *string `json:"gitCredentials,omitempty" tf:"git_credentials,omitempty"`

	// (String)
	LastFetchedAt *string `json:"lastFetchedAt,omitempty" tf:"last_fetched_at,omitempty"`

	// (String) Specifies the identifier for the git repository; must be unique for the schema in which the git repository is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type DescribeOutputParameters struct {
}

type RepositoryInitParameters struct {

	// (String) Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	// Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	APIIntegration *string `json:"apiIntegration,omitempty" tf:"api_integration,omitempty"`

	// (String) Specifies a comment for the git repository.
	// Specifies a comment for the git repository.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the git repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the git repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Specifies the Snowflake secret fully qualified name (e.g "\"<db_name>\".\"<schema_name>\".\"<secret_name>\"") containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	// Specifies the Snowflake secret fully qualified name (e.g `"\"<db_name>\".\"<schema_name>\".\"<secret_name>\""`) containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	GitCredentials *string `json:"gitCredentials,omitempty" tf:"git_credentials,omitempty"`

	// (String) Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	// Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String) The schema in which to create the git repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the git repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type RepositoryObservation struct {

	// (String) Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	// Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	APIIntegration *string `json:"apiIntegration,omitempty" tf:"api_integration,omitempty"`

	// (String) Specifies a comment for the git repository.
	// Specifies a comment for the git repository.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the git repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the git repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE GIT REPOSITORY for the given git repository. (see below for nested schema)
	// Outputs the result of `DESCRIBE GIT REPOSITORY` for the given git repository.
	DescribeOutput []DescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) Specifies the Snowflake secret fully qualified name (e.g "\"<db_name>\".\"<schema_name>\".\"<secret_name>\"") containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	// Specifies the Snowflake secret fully qualified name (e.g `"\"<db_name>\".\"<schema_name>\".\"<secret_name>\""`) containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	GitCredentials *string `json:"gitCredentials,omitempty" tf:"git_credentials,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	// Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String) The schema in which to create the git repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the git repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (List of Object) Outputs the result of SHOW GIT REPOSITORIES for the given git repository. (see below for nested schema)
	// Outputs the result of `SHOW GIT REPOSITORIES` for the given git repository.
	ShowOutput []ShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type RepositoryParameters struct {

	// (String) Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	// Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	// +kubebuilder:validation:Optional
	APIIntegration *string `json:"apiIntegration,omitempty" tf:"api_integration,omitempty"`

	// (String) Specifies a comment for the git repository.
	// Specifies a comment for the git repository.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the git repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the git repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (String) Specifies the Snowflake secret fully qualified name (e.g "\"<db_name>\".\"<schema_name>\".\"<secret_name>\"") containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	// Specifies the Snowflake secret fully qualified name (e.g `"\"<db_name>\".\"<schema_name>\".\"<secret_name>\""`) containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	// +kubebuilder:validation:Optional
	GitCredentials *string `json:"gitCredentials,omitempty" tf:"git_credentials,omitempty"`

	// (String) Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	// Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	// +kubebuilder:validation:Optional
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String) The schema in which to create the git repository. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the git repository. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type ShowOutputInitParameters struct {
}

type ShowOutputObservation struct {

	// (String) Identifier of API INTEGRATION containing information about the remote Git repository such as allowed credentials and prefixes for target URLs.
	APIIntegration *string `json:"apiIntegration,omitempty" tf:"api_integration,omitempty"`

	// (String) Specifies a comment for the git repository.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (String) Specifies the Snowflake secret fully qualified name (e.g "\"<db_name>\".\"<schema_name>\".\"<secret_name>\"") containing the credentials to use for authenticating with the remote Git repository. Omit this parameter to use the default secret specified by the API integration or if this integration does not require authentication.
	GitCredentials *string `json:"gitCredentials,omitempty" tf:"git_credentials,omitempty"`

	// (String)
	LastFetchedAt *string `json:"lastFetchedAt,omitempty" tf:"last_fetched_at,omitempty"`

	// (String) Specifies the identifier for the git repository; must be unique for the schema in which the git repository is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Specifies the origin URL of the remote Git repository that this Git repository clone represents. The URL must use HTTPS.
	Origin *string `json:"origin,omitempty" tf:"origin,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`
}

type ShowOutputParameters struct {
}

// RepositorySpec defines the desired state of Repository
type RepositorySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RepositoryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RepositoryInitParameters `json:"initProvider,omitempty"`
}

// RepositoryStatus defines the observed state of Repository.
type RepositoryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RepositoryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Repository is the Schema for the Repositorys API. Resource used to manage git repositories. For more information, check git repositories documentation https://docs.snowflake.com/en/sql-reference/sql/create-git-repository.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Repository struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.apiIntegration) || (has(self.initProvider) && has(self.initProvider.apiIntegration))",message="spec.forProvider.apiIntegration is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.origin) || (has(self.initProvider) && has(self.initProvider.origin))",message="spec.forProvider.origin is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	Spec   RepositorySpec   `json:"spec"`
	Status RepositoryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RepositoryList contains a list of Repositorys
type RepositoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Repository `json:"items"`
}

// Repository type metadata.
var (
	Repository_Kind             = "Repository"
	Repository_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Repository_Kind}.String()
	Repository_KindAPIVersion   = Repository_Kind + "." + CRDGroupVersion.String()
	Repository_GroupVersionKind = CRDGroupVersion.WithKind(Repository_Kind)
)

func init() {
	SchemeBuilder.Register(&Repository{}, &RepositoryList{})
}
