apiVersion: compute.crossplane.io/v1alpha1
kind: Pool
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/pool
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    instanceFamily: CPU_X64_S
    maxNodes: 2
    minNodes: 1
