apiVersion: git.crossplane.io/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/repository
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    apiIntegration: API_INTEGRATION
    database: DATABASE
    origin: https://github.com/user/repo
    schema: SCHEMA
