// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Java) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Javascript) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Python) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Scala) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SQL) Hub() {}
