// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ArgumentsInitParameters struct {

	// (String) The argument type.
	// The argument type.
	ArgDataType *string `json:"argDataType,omitempty" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	ArgName *string `json:"argName,omitempty" tf:"arg_name,omitempty"`
}

type ArgumentsObservation struct {

	// (String) The argument type.
	// The argument type.
	ArgDataType *string `json:"argDataType,omitempty" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	ArgName *string `json:"argName,omitempty" tf:"arg_name,omitempty"`
}

type ArgumentsParameters struct {

	// (String) The argument type.
	// The argument type.
	// +kubebuilder:validation:Optional
	ArgDataType *string `json:"argDataType" tf:"arg_data_type,omitempty"`

	// Optional default value for the argument. For text values use single quotes. Numeric values can be unquoted. External changes for this field won't be detected.
	// +kubebuilder:validation:Optional
	ArgDefaultValue *string `json:"argDefaultValue,omitempty" tf:"arg_default_value,omitempty"`

	// (String) The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// The argument name. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the procedure definition.
	// +kubebuilder:validation:Optional
	ArgName *string `json:"argName" tf:"arg_name,omitempty"`
}

type EnableConsoleOutputInitParameters struct {
}

type EnableConsoleOutputObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EnableConsoleOutputParameters struct {
}

type ImportsInitParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type ImportsObservation struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type ImportsParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	// +kubebuilder:validation:Optional
	PathOnStage *string `json:"pathOnStage" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	// +kubebuilder:validation:Optional
	StageLocation *string `json:"stageLocation" tf:"stage_location,omitempty"`
}

type JavaInitParameters struct {

	// (Block List) List of the arguments for the procedure. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the procedure. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-procedure#all-languages) for more details.
	Arguments []ArgumentsInitParameters `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined procedure) Specifies a comment for the procedure.
	// (Default: `user-defined procedure`) Specifies a comment for the procedure.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): CALLER | OWNER.
	// Specifies whether the stored procedure executes with the privileges of the owner (an “owner’s rights” stored procedure) or with the privileges of the caller (a “caller’s rights” stored procedure). If you execute the statement CREATE PROCEDURE … EXECUTE AS CALLER, then in the future the procedure will execute as a caller’s rights procedure. If you execute CREATE PROCEDURE … EXECUTE AS OWNER, then the procedure will execute as an owner’s rights procedure. For more information, see [Understanding caller’s rights and owner’s rights stored procedures](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-rights). Valid values are (case-insensitive): `CALLER` | `OWNER`.
	ExecuteAs *string `json:"executeAs,omitempty" tf:"execute_as,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this procedure’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// The names of [external access integrations](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) needed in order for this procedure’s handler code to access external networks. An external access integration specifies [network rules](https://docs.snowflake.com/en/sql-reference/sql/create-network-rule) and [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (String) Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form com.my_company.my_package.MyClass.myMethod where com.my_company.my_package corresponds to the package containing the object or class: package com.my_company.my_package;.
	// Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form `com.my_company.my_package.MyClass.myMethod` where `com.my_company.my_package` corresponds to the package containing the object or class: `package com.my_company.my_package;`.
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// line stored procedure, you can omit this clause, unless your code depends on classes defined outside the stored procedure or resource files. If you are writing a stored procedure with a staged handler, you must also include a path to the JAR file containing the stored procedure’s handler code. The IMPORTS definition cannot reference variables from arguments that are passed into the stored procedure. Each file in the IMPORTS clause must have a unique name, even if the files are in different subdirectories or different stages. (see below for nested schema)
	// The location (stage), path, and name of the file(s) to import. You must set the IMPORTS clause to include any files that your stored procedure depends on. If you are writing an in-line stored procedure, you can omit this clause, unless your code depends on classes defined outside the stored procedure or resource files. If you are writing a stored procedure with a staged handler, you must also include a path to the JAR file containing the stored procedure’s handler code. The IMPORTS definition cannot reference variables from arguments that are passed into the stored procedure. Each file in the IMPORTS clause must have a unique name, even if the files are in different subdirectories or different stages.
	Imports []ImportsInitParameters `json:"imports,omitempty" tf:"imports,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the procedure is secure. For more information about secure procedures, see [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake.com/en/developer-guide/secure-udf-procedure). Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the procedure when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (Set of String) List of the names of packages deployed in Snowflake that should be included in the handler code’s execution environment. The Snowpark package is required for stored procedures, but is specified in the snowpark_package attribute. For more information about Snowpark, see Snowpark API.
	// List of the names of packages deployed in Snowflake that should be included in the handler code’s execution environment. The Snowpark package is required for stored procedures, but is specified in the `snowpark_package` attribute. For more information about Snowpark, see [Snowpark API](https://docs.snowflake.com/en/developer-guide/snowpark/index).
	// +listType=set
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// (String) Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping $$ signs are added by the provider automatically; do not include them. The procedure_definition value must be Java source code. For more information, see Java (using Snowpark). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping `$$` signs are added by the provider automatically; do not include them. The `procedure_definition` value must be Java source code. For more information, see [Java (using Snowpark)](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-java). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	ProcedureDefinition *string `json:"procedureDefinition,omitempty" tf:"procedure_definition,omitempty"`

	// Java Data Type Mappings). For RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] ), if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. TABLE ()).
	// Specifies the type of the result returned by the stored procedure. For `<result_data_type>`, use the Snowflake data type that corresponds to the type of the language that you are using (see [SQL-Java Data Type Mappings](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-data-type-mapping.html#label-sql-java-data-type-mappings)). For `RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] )`, if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. `TABLE ()`).
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) The language runtime version to use. Currently, the supported versions are: 11.
	// The language runtime version to use. Currently, the supported versions are: 11.
	RuntimeVersion *string `json:"runtimeVersion,omitempty" tf:"runtime_version,omitempty"`

	// (String) The schema in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	// Assigns the names of [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the [external access integration](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter.
	Secrets []SecretsInitParameters `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (String) The Snowpark package is required for stored procedures, so it must always be present. For more information about Snowpark, see Snowpark API.
	// The Snowpark package is required for stored procedures, so it must always be present. For more information about Snowpark, see [Snowpark API](https://docs.snowflake.com/en/developer-guide/snowpark/index).
	SnowparkPackage *string `json:"snowparkPackage,omitempty" tf:"snowpark_package,omitempty"`

	// (Block Set, Max: 1) Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form com.my_company.my_package.MyClass.myMethod where com.my_company.my_package corresponds to the package containing the object or class: package com.my_company.my_package;. (see below for nested schema)
	// Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form `com.my_company.my_package.MyClass.myMethod` where `com.my_company.my_package` corresponds to the package containing the object or class: `package com.my_company.my_package;`.
	TargetPath []TargetPathInitParameters `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type JavaObservation struct {

	// (Block List) List of the arguments for the procedure. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the procedure. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-procedure#all-languages) for more details.
	Arguments []ArgumentsObservation `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined procedure) Specifies a comment for the procedure.
	// (Default: `user-defined procedure`) Specifies a comment for the procedure.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): CALLER | OWNER.
	// Specifies whether the stored procedure executes with the privileges of the owner (an “owner’s rights” stored procedure) or with the privileges of the caller (a “caller’s rights” stored procedure). If you execute the statement CREATE PROCEDURE … EXECUTE AS CALLER, then in the future the procedure will execute as a caller’s rights procedure. If you execute CREATE PROCEDURE … EXECUTE AS OWNER, then the procedure will execute as an owner’s rights procedure. For more information, see [Understanding caller’s rights and owner’s rights stored procedures](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-rights). Valid values are (case-insensitive): `CALLER` | `OWNER`.
	ExecuteAs *string `json:"executeAs,omitempty" tf:"execute_as,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this procedure’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// The names of [external access integrations](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) needed in order for this procedure’s handler code to access external networks. An external access integration specifies [network rules](https://docs.snowflake.com/en/sql-reference/sql/create-network-rule) and [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form com.my_company.my_package.MyClass.myMethod where com.my_company.my_package corresponds to the package containing the object or class: package com.my_company.my_package;.
	// Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form `com.my_company.my_package.MyClass.myMethod` where `com.my_company.my_package` corresponds to the package containing the object or class: `package com.my_company.my_package;`.
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// line stored procedure, you can omit this clause, unless your code depends on classes defined outside the stored procedure or resource files. If you are writing a stored procedure with a staged handler, you must also include a path to the JAR file containing the stored procedure’s handler code. The IMPORTS definition cannot reference variables from arguments that are passed into the stored procedure. Each file in the IMPORTS clause must have a unique name, even if the files are in different subdirectories or different stages. (see below for nested schema)
	// The location (stage), path, and name of the file(s) to import. You must set the IMPORTS clause to include any files that your stored procedure depends on. If you are writing an in-line stored procedure, you can omit this clause, unless your code depends on classes defined outside the stored procedure or resource files. If you are writing a stored procedure with a staged handler, you must also include a path to the JAR file containing the stored procedure’s handler code. The IMPORTS definition cannot reference variables from arguments that are passed into the stored procedure. Each file in the IMPORTS clause must have a unique name, even if the files are in different subdirectories or different stages.
	Imports []ImportsObservation `json:"imports,omitempty" tf:"imports,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the procedure is secure. For more information about secure procedures, see [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake.com/en/developer-guide/secure-udf-procedure). Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the procedure when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (Set of String) List of the names of packages deployed in Snowflake that should be included in the handler code’s execution environment. The Snowpark package is required for stored procedures, but is specified in the snowpark_package attribute. For more information about Snowpark, see Snowpark API.
	// List of the names of packages deployed in Snowflake that should be included in the handler code’s execution environment. The Snowpark package is required for stored procedures, but is specified in the `snowpark_package` attribute. For more information about Snowpark, see [Snowpark API](https://docs.snowflake.com/en/developer-guide/snowpark/index).
	// +listType=set
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// (List of Object) Outputs the result of SHOW PARAMETERS IN PROCEDURE for the given procedure. (see below for nested schema)
	// Outputs the result of `SHOW PARAMETERS IN PROCEDURE` for the given procedure.
	Parameters []ParametersObservation `json:"parameters,omitempty" tf:"parameters,omitempty"`

	// (String) Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping $$ signs are added by the provider automatically; do not include them. The procedure_definition value must be Java source code. For more information, see Java (using Snowpark). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping `$$` signs are added by the provider automatically; do not include them. The `procedure_definition` value must be Java source code. For more information, see [Java (using Snowpark)](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-java). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	ProcedureDefinition *string `json:"procedureDefinition,omitempty" tf:"procedure_definition,omitempty"`

	// (String) Specifies language for the procedure. Used to detect external changes.
	// Specifies language for the procedure. Used to detect external changes.
	ProcedureLanguage *string `json:"procedureLanguage,omitempty" tf:"procedure_language,omitempty"`

	// Java Data Type Mappings). For RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] ), if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. TABLE ()).
	// Specifies the type of the result returned by the stored procedure. For `<result_data_type>`, use the Snowflake data type that corresponds to the type of the language that you are using (see [SQL-Java Data Type Mappings](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-data-type-mapping.html#label-sql-java-data-type-mappings)). For `RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] )`, if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. `TABLE ()`).
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) The language runtime version to use. Currently, the supported versions are: 11.
	// The language runtime version to use. Currently, the supported versions are: 11.
	RuntimeVersion *string `json:"runtimeVersion,omitempty" tf:"runtime_version,omitempty"`

	// (String) The schema in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	// Assigns the names of [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the [external access integration](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter.
	Secrets []SecretsObservation `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (List of Object) Outputs the result of SHOW PROCEDURE for the given procedure. (see below for nested schema)
	// Outputs the result of `SHOW PROCEDURE` for the given procedure.
	ShowOutput []ShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`

	// (String) The Snowpark package is required for stored procedures, so it must always be present. For more information about Snowpark, see Snowpark API.
	// The Snowpark package is required for stored procedures, so it must always be present. For more information about Snowpark, see [Snowpark API](https://docs.snowflake.com/en/developer-guide/snowpark/index).
	SnowparkPackage *string `json:"snowparkPackage,omitempty" tf:"snowpark_package,omitempty"`

	// (Block Set, Max: 1) Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form com.my_company.my_package.MyClass.myMethod where com.my_company.my_package corresponds to the package containing the object or class: package com.my_company.my_package;. (see below for nested schema)
	// Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form `com.my_company.my_package.MyClass.myMethod` where `com.my_company.my_package` corresponds to the package containing the object or class: `package com.my_company.my_package;`.
	TargetPath []TargetPathObservation `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type JavaParameters struct {

	// (Block List) List of the arguments for the procedure. Consult the docs for more details. (see below for nested schema)
	// List of the arguments for the procedure. Consult the [docs](https://docs.snowflake.com/en/sql-reference/sql/create-procedure#all-languages) for more details.
	// +kubebuilder:validation:Optional
	Arguments []ArgumentsParameters `json:"arguments,omitempty" tf:"arguments,omitempty"`

	// defined procedure) Specifies a comment for the procedure.
	// (Default: `user-defined procedure`) Specifies a comment for the procedure.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) The database in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	// Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check [ENABLE_CONSOLE_OUTPUT docs](https://docs.snowflake.com/en/sql-reference/parameters#enable-console-output).
	// +kubebuilder:validation:Optional
	EnableConsoleOutput *bool `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// insensitive): CALLER | OWNER.
	// Specifies whether the stored procedure executes with the privileges of the owner (an “owner’s rights” stored procedure) or with the privileges of the caller (a “caller’s rights” stored procedure). If you execute the statement CREATE PROCEDURE … EXECUTE AS CALLER, then in the future the procedure will execute as a caller’s rights procedure. If you execute CREATE PROCEDURE … EXECUTE AS OWNER, then the procedure will execute as an owner’s rights procedure. For more information, see [Understanding caller’s rights and owner’s rights stored procedures](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-rights). Valid values are (case-insensitive): `CALLER` | `OWNER`.
	// +kubebuilder:validation:Optional
	ExecuteAs *string `json:"executeAs,omitempty" tf:"execute_as,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this procedure’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// The names of [external access integrations](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) needed in order for this procedure’s handler code to access external networks. An external access integration specifies [network rules](https://docs.snowflake.com/en/sql-reference/sql/create-network-rule) and [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	// +kubebuilder:validation:Optional
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (String) Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form com.my_company.my_package.MyClass.myMethod where com.my_company.my_package corresponds to the package containing the object or class: package com.my_company.my_package;.
	// Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form `com.my_company.my_package.MyClass.myMethod` where `com.my_company.my_package` corresponds to the package containing the object or class: `package com.my_company.my_package;`.
	// +kubebuilder:validation:Optional
	Handler *string `json:"handler,omitempty" tf:"handler,omitempty"`

	// line stored procedure, you can omit this clause, unless your code depends on classes defined outside the stored procedure or resource files. If you are writing a stored procedure with a staged handler, you must also include a path to the JAR file containing the stored procedure’s handler code. The IMPORTS definition cannot reference variables from arguments that are passed into the stored procedure. Each file in the IMPORTS clause must have a unique name, even if the files are in different subdirectories or different stages. (see below for nested schema)
	// The location (stage), path, and name of the file(s) to import. You must set the IMPORTS clause to include any files that your stored procedure depends on. If you are writing an in-line stored procedure, you can omit this clause, unless your code depends on classes defined outside the stored procedure or resource files. If you are writing a stored procedure with a staged handler, you must also include a path to the JAR file containing the stored procedure’s handler code. The IMPORTS definition cannot reference variables from arguments that are passed into the stored procedure. Each file in the IMPORTS clause must have a unique name, even if the files are in different subdirectories or different stages.
	// +kubebuilder:validation:Optional
	Imports []ImportsParameters `json:"imports,omitempty" tf:"imports,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies that the procedure is secure. For more information about secure procedures, see [Protecting Sensitive Information with Secure UDFs and Stored Procedures](https://docs.snowflake.com/en/developer-guide/secure-udf-procedure). Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	IsSecure *string `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	// LOG_LEVEL to use when filtering events For more information, check [LOG_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#log-level).
	// +kubebuilder:validation:Optional
	LogLevel *string `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	// METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check [METRIC_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#metric-level).
	// +kubebuilder:validation:Optional
	MetricLevel *string `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// insensitive): CALLED ON NULL INPUT | RETURNS NULL ON NULL INPUT.
	// Specifies the behavior of the procedure when called with null inputs. Valid values are (case-insensitive): `CALLED ON NULL INPUT` | `RETURNS NULL ON NULL INPUT`.
	// +kubebuilder:validation:Optional
	NullInputBehavior *string `json:"nullInputBehavior,omitempty" tf:"null_input_behavior,omitempty"`

	// (Set of String) List of the names of packages deployed in Snowflake that should be included in the handler code’s execution environment. The Snowpark package is required for stored procedures, but is specified in the snowpark_package attribute. For more information about Snowpark, see Snowpark API.
	// List of the names of packages deployed in Snowflake that should be included in the handler code’s execution environment. The Snowpark package is required for stored procedures, but is specified in the `snowpark_package` attribute. For more information about Snowpark, see [Snowpark API](https://docs.snowflake.com/en/developer-guide/snowpark/index).
	// +kubebuilder:validation:Optional
	// +listType=set
	Packages []*string `json:"packages,omitempty" tf:"packages,omitempty"`

	// (String) Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping $$ signs are added by the provider automatically; do not include them. The procedure_definition value must be Java source code. For more information, see Java (using Snowpark). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// Defines the code executed by the stored procedure. The definition can consist of any valid code. Wrapping `$$` signs are added by the provider automatically; do not include them. The `procedure_definition` value must be Java source code. For more information, see [Java (using Snowpark)](https://docs.snowflake.com/en/developer-guide/stored-procedure/stored-procedures-java). To mitigate permadiff on this field, the provider replaces blank characters with a space. This can lead to false positives in cases where a change in case or run of whitespace is semantically significant.
	// +kubebuilder:validation:Optional
	ProcedureDefinition *string `json:"procedureDefinition,omitempty" tf:"procedure_definition,omitempty"`

	// Java Data Type Mappings). For RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] ), if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. TABLE ()).
	// Specifies the type of the result returned by the stored procedure. For `<result_data_type>`, use the Snowflake data type that corresponds to the type of the language that you are using (see [SQL-Java Data Type Mappings](https://docs.snowflake.com/en/developer-guide/udf-stored-procedure-data-type-mapping.html#label-sql-java-data-type-mappings)). For `RETURNS TABLE ( [ col_name col_data_type [ , ... ] ] )`, if you know the Snowflake data types of the columns in the returned table, specify the column names and types. Otherwise (e.g. if you are determining the column types during run time), you can omit the column names and types (i.e. `TABLE ()`).
	// +kubebuilder:validation:Optional
	ReturnType *string `json:"returnType,omitempty" tf:"return_type,omitempty"`

	// (String) The language runtime version to use. Currently, the supported versions are: 11.
	// The language runtime version to use. Currently, the supported versions are: 11.
	// +kubebuilder:validation:Optional
	RuntimeVersion *string `json:"runtimeVersion,omitempty" tf:"runtime_version,omitempty"`

	// (String) The schema in which to create the procedure. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the procedure. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	// Assigns the names of [secrets](https://docs.snowflake.com/en/sql-reference/sql/create-secret) to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the [external access integration](https://docs.snowflake.com/en/sql-reference/sql/create-external-access-integration) specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// +kubebuilder:validation:Optional
	Secrets []SecretsParameters `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (String) The Snowpark package is required for stored procedures, so it must always be present. For more information about Snowpark, see Snowpark API.
	// The Snowpark package is required for stored procedures, so it must always be present. For more information about Snowpark, see [Snowpark API](https://docs.snowflake.com/en/developer-guide/snowpark/index).
	// +kubebuilder:validation:Optional
	SnowparkPackage *string `json:"snowparkPackage,omitempty" tf:"snowpark_package,omitempty"`

	// (Block Set, Max: 1) Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form com.my_company.my_package.MyClass.myMethod where com.my_company.my_package corresponds to the package containing the object or class: package com.my_company.my_package;. (see below for nested schema)
	// Use the fully qualified name of the method or function for the stored procedure. This is typically in the following form `com.my_company.my_package.MyClass.myMethod` where `com.my_company.my_package` corresponds to the package containing the object or class: `package com.my_company.my_package;`.
	// +kubebuilder:validation:Optional
	TargetPath []TargetPathParameters `json:"targetPath,omitempty" tf:"target_path,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	// Trace level value to use when generating/filtering trace events For more information, check [TRACE_LEVEL docs](https://docs.snowflake.com/en/sql-reference/parameters#trace-level).
	// +kubebuilder:validation:Optional
	TraceLevel *string `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type LogLevelInitParameters struct {
}

type LogLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type LogLevelParameters struct {
}

type MetricLevelInitParameters struct {
}

type MetricLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type MetricLevelParameters struct {
}

type ParametersInitParameters struct {
}

type ParametersObservation struct {

	// (Boolean) Enable stdout/stderr fast path logging for anonyous stored procs. This is a public parameter (similar to LOG_LEVEL). For more information, check ENABLE_CONSOLE_OUTPUT docs.
	EnableConsoleOutput []EnableConsoleOutputObservation `json:"enableConsoleOutput,omitempty" tf:"enable_console_output,omitempty"`

	// (String) LOG_LEVEL to use when filtering events For more information, check LOG_LEVEL docs.
	LogLevel []LogLevelObservation `json:"logLevel,omitempty" tf:"log_level,omitempty"`

	// (String) METRIC_LEVEL value to control whether to emit metrics to Event Table For more information, check METRIC_LEVEL docs.
	MetricLevel []MetricLevelObservation `json:"metricLevel,omitempty" tf:"metric_level,omitempty"`

	// (String) Trace level value to use when generating/filtering trace events For more information, check TRACE_LEVEL docs.
	TraceLevel []TraceLevelObservation `json:"traceLevel,omitempty" tf:"trace_level,omitempty"`
}

type ParametersParameters struct {
}

type SecretsInitParameters struct {

	// (String) Fully qualified name of the allowed secret. You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// Fully qualified name of the allowed [secret](https://docs.snowflake.com/en/sql-reference/sql/create-secret). You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The variable that will be used in handler code when retrieving information from the secret.
	// The variable that will be used in handler code when retrieving information from the secret.
	SecretVariableName *string `json:"secretVariableName,omitempty" tf:"secret_variable_name,omitempty"`
}

type SecretsObservation struct {

	// (String) Fully qualified name of the allowed secret. You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// Fully qualified name of the allowed [secret](https://docs.snowflake.com/en/sql-reference/sql/create-secret). You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	SecretID *string `json:"secretId,omitempty" tf:"secret_id,omitempty"`

	// (String) The variable that will be used in handler code when retrieving information from the secret.
	// The variable that will be used in handler code when retrieving information from the secret.
	SecretVariableName *string `json:"secretVariableName,omitempty" tf:"secret_variable_name,omitempty"`
}

type SecretsParameters struct {

	// (String) Fully qualified name of the allowed secret. You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// Fully qualified name of the allowed [secret](https://docs.snowflake.com/en/sql-reference/sql/create-secret). You will receive an error if you specify a SECRETS value whose secret isn’t also included in an integration specified by the EXTERNAL_ACCESS_INTEGRATIONS parameter.
	// +kubebuilder:validation:Optional
	SecretID *string `json:"secretId" tf:"secret_id,omitempty"`

	// (String) The variable that will be used in handler code when retrieving information from the secret.
	// The variable that will be used in handler code when retrieving information from the secret.
	// +kubebuilder:validation:Optional
	SecretVariableName *string `json:"secretVariableName" tf:"secret_variable_name,omitempty"`
}

type ShowOutputInitParameters struct {
}

type ShowOutputObservation struct {

	// (String)
	ArgumentsRaw *string `json:"argumentsRaw,omitempty" tf:"arguments_raw,omitempty"`

	// (String)
	CatalogName *string `json:"catalogName,omitempty" tf:"catalog_name,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Set of String) The names of external access integrations needed in order for this procedure’s handler code to access external networks. An external access integration specifies network rules and secrets that specify external locations and credentials (if any) allowed for use by handler code when making requests of an external network, such as an external REST API.
	ExternalAccessIntegrations *string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Boolean)
	IsAggregate *bool `json:"isAggregate,omitempty" tf:"is_aggregate,omitempty"`

	// (Boolean)
	IsAnsi *bool `json:"isAnsi,omitempty" tf:"is_ansi,omitempty"`

	// (Boolean)
	IsBuiltin *bool `json:"isBuiltin,omitempty" tf:"is_builtin,omitempty"`

	// uses special value that cannot be set in the configuration manually (default)) Specifies that the procedure is secure. For more information about secure procedures, see Protecting Sensitive Information with Secure UDFs and Stored Procedures. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	IsSecure *bool `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// (Boolean)
	IsTableFunction *bool `json:"isTableFunction,omitempty" tf:"is_table_function,omitempty"`

	// (Number)
	MaxNumArguments *float64 `json:"maxNumArguments,omitempty" tf:"max_num_arguments,omitempty"`

	// (Number)
	MinNumArguments *float64 `json:"minNumArguments,omitempty" tf:"min_num_arguments,omitempty"`

	// (String) The name of the procedure; the identifier does not need to be unique for the schema in which the procedure is created because stored procedures are identified and resolved by the combination of the name and argument types. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (Block Set) Assigns the names of secrets to variables so that you can use the variables to reference the secrets when retrieving information from secrets in handler code. Secrets you specify here must be allowed by the external access integration specified as a value of this CREATE FUNCTION command’s EXTERNAL_ACCESS_INTEGRATIONS parameter. (see below for nested schema)
	Secrets *string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// (Boolean)
	ValidForClustering *bool `json:"validForClustering,omitempty" tf:"valid_for_clustering,omitempty"`
}

type ShowOutputParameters struct {
}

type TargetPathInitParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type TargetPathObservation struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	PathOnStage *string `json:"pathOnStage,omitempty" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	StageLocation *string `json:"stageLocation,omitempty" tf:"stage_location,omitempty"`
}

type TargetPathParameters struct {

	// (String) Path for import on stage, without the leading /.
	// Path for import on stage, without the leading `/`.
	// +kubebuilder:validation:Optional
	PathOnStage *string `json:"pathOnStage" tf:"path_on_stage,omitempty"`

	// (String) Stage location without leading @. To use your user's stage set this to ~, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use snowflake_stage.<your stage's resource name>.
	// Stage location without leading `@`. To use your user's stage set this to `~`, otherwise pass fully qualified name of the stage (with every part contained in double quotes or use `snowflake_stage.<your stage's resource name>.
	// +kubebuilder:validation:Optional
	StageLocation *string `json:"stageLocation" tf:"stage_location,omitempty"`
}

type TraceLevelInitParameters struct {
}

type TraceLevelObservation struct {

	// (String)
	Default *string `json:"default,omitempty" tf:"default,omitempty"`

	// (String)
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String)
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String)
	Level *string `json:"level,omitempty" tf:"level,omitempty"`

	// (String)
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type TraceLevelParameters struct {
}

// JavaSpec defines the desired state of Java
type JavaSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     JavaParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider JavaInitParameters `json:"initProvider,omitempty"`
}

// JavaStatus defines the observed state of Java.
type JavaStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        JavaObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Java is the Schema for the Javas API. Resource used to manage java procedure objects. For more information, check procedure documentation https://docs.snowflake.com/en/sql-reference/sql/create-procedure.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Java struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.handler) || (has(self.initProvider) && has(self.initProvider.handler))",message="spec.forProvider.handler is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.returnType) || (has(self.initProvider) && has(self.initProvider.returnType))",message="spec.forProvider.returnType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runtimeVersion) || (has(self.initProvider) && has(self.initProvider.runtimeVersion))",message="spec.forProvider.runtimeVersion is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.snowparkPackage) || (has(self.initProvider) && has(self.initProvider.snowparkPackage))",message="spec.forProvider.snowparkPackage is a required parameter"
	Spec   JavaSpec   `json:"spec"`
	Status JavaStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// JavaList contains a list of Javas
type JavaList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Java `json:"items"`
}

// Repository type metadata.
var (
	Java_Kind             = "Java"
	Java_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Java_Kind}.String()
	Java_KindAPIVersion   = Java_Kind + "." + CRDGroupVersion.String()
	Java_GroupVersionKind = CRDGroupVersion.WithKind(Java_Kind)
)

func init() {
	SchemeBuilder.Register(&Java{}, &JavaList{})
}
