apiVersion: snowflakesecretwithbasicauthentication.crossplane.io/v1alpha1
kind: WithBasicAuthentication
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakesecretwithbasicauthentication/v1alpha1/withbasicauthentication
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    database: EXAMPLE_DB
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    schema: EXAMPLE_SCHEMA
    usernameSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
