apiVersion: procedure.crossplane.io/v1alpha1
kind: Javascript
metadata:
  annotations:
    meta.upbound.io/example-id: procedure/v1alpha1/javascript
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    arguments:
    - argDataType: VARCHAR(100)
      argName: x
    database: Database
    procedureDefinition: |2
        if (x == 0) {
          return 1;
        } else {
          return 2;
        }
    returnType: VARCHAR(100)
    schema: Schema
