apiVersion: procedure.crossplane.io/v1alpha1
kind: Python
metadata:
  annotations:
    meta.upbound.io/example-id: procedure/v1alpha1/python
  labels:
    testing.upbound.io/example-name: w
  name: w
spec:
  forProvider:
    arguments:
    - argDataType: VARCHAR(100)
      argName: x
    database: Database
    handler: echoVarchar
    procedureDefinition: |2
        def echoVarchar(x):
        result = ''
        for a in range(5):
          result += x
        return result
    returnType: VARCHAR(100)
    runtimeVersion: "3.9"
    schema: Schema
    snowparkPackage: 1.14.0
