apiVersion: procedure.crossplane.io/v1alpha1
kind: Scala
metadata:
  annotations:
    meta.upbound.io/example-id: procedure/v1alpha1/scala
  labels:
    testing.upbound.io/example-name: w
  name: w
spec:
  forProvider:
    arguments:
    - argDataType: VARCHAR(100)
      argName: x
    database: Database
    handler: TestFunc.echoVarchar
    procedureDefinition: |2
        import com.snowflake.snowpark_java.Session
        class TestFunc {
          def echoVarchar(session : Session, x : String): String = {
            return x
          }
        }
    returnType: VARCHAR(100)
    runtimeVersion: "2.12"
    schema: Schema
    snowparkPackage: 1.14.0
