apiVersion: procedure.crossplane.io/v1alpha1
kind: SQL
metadata:
  annotations:
    meta.upbound.io/example-id: procedure/v1alpha1/sql
  labels:
    testing.upbound.io/example-name: w
  name: w
spec:
  forProvider:
    arguments:
    - argDataType: VARCHAR(100)
      argName: x
    database: Database
    procedureDefinition: |
      BEGIN
        RETURN message;
      END;
    returnType: VARCHAR(100)
    schema: Schema
