// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ConstraintInitParameters struct {

	// (List of String) Columns to use in constraint key
	// Columns to use in constraint key
	Columns []*string `json:"columns,omitempty" tf:"columns,omitempty"`

	// (String, Deprecated) Comment for the table constraint
	// Comment for the table constraint
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) (Default: true) Whether the constraint is deferrable
	// (Default: `true`) Whether the constraint is deferrable
	Deferrable *bool `json:"deferrable,omitempty" tf:"deferrable,omitempty"`

	// (Boolean) (Default: true) Specifies whether the constraint is enabled or disabled. These properties are provided for compatibility with Oracle.
	// (Default: `true`) Specifies whether the constraint is enabled or disabled. These properties are provided for compatibility with Oracle.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// (Boolean) (Default: false) Whether the constraint is enforced
	// (Default: `false`) Whether the constraint is enforced
	Enforced *bool `json:"enforced,omitempty" tf:"enforced,omitempty"`

	// (Block List, Max: 1) Additional properties when type is set to foreign key. Not applicable for primary/unique keys (see below for nested schema)
	// Additional properties when type is set to foreign key. Not applicable for primary/unique keys
	ForeignKeyProperties []ForeignKeyPropertiesInitParameters `json:"foreignKeyProperties,omitempty" tf:"foreign_key_properties,omitempty"`

	// (String) (Default: DEFERRED) Whether the constraint is initially deferred or immediate
	// (Default: `DEFERRED`) Whether the constraint is initially deferred or immediate
	Initially *string `json:"initially,omitempty" tf:"initially,omitempty"`

	// (Boolean) (Default: true) Specifies whether a constraint in NOVALIDATE mode is taken into account during query rewrite.
	// (Default: `true`) Specifies whether a constraint in NOVALIDATE mode is taken into account during query rewrite.
	Rely *bool `json:"rely,omitempty" tf:"rely,omitempty"`

	// (String) Identifier for table to create constraint on. Format must follow: ""<db_name>"."<schema_name>"."<table_name>"" or "<db_name>.<schema_name>.<table_name>" (snowflake_table.my_table.id)
	// Identifier for table to create constraint on. Format must follow: "\"&lt;db_name&gt;\".\"&lt;schema_name&gt;\".\"&lt;table_name&gt;\"" or "&lt;db_name&gt;.&lt;schema_name&gt;.&lt;table_name&gt;" (snowflake_table.my_table.id)
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// (String) Type of constraint, one of 'UNIQUE', 'PRIMARY KEY', or 'FOREIGN KEY'
	// Type of constraint, one of 'UNIQUE', 'PRIMARY KEY', or 'FOREIGN KEY'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Boolean) (Default: false) Specifies whether to validate existing data on the table when a constraint is created. Only used in conjunction with the ENABLE property.
	// (Default: `false`) Specifies whether to validate existing data on the table when a constraint is created. Only used in conjunction with the ENABLE property.
	Validate *bool `json:"validate,omitempty" tf:"validate,omitempty"`
}

type ConstraintObservation struct {

	// (List of String) Columns to use in constraint key
	// Columns to use in constraint key
	Columns []*string `json:"columns,omitempty" tf:"columns,omitempty"`

	// (String, Deprecated) Comment for the table constraint
	// Comment for the table constraint
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) (Default: true) Whether the constraint is deferrable
	// (Default: `true`) Whether the constraint is deferrable
	Deferrable *bool `json:"deferrable,omitempty" tf:"deferrable,omitempty"`

	// (Boolean) (Default: true) Specifies whether the constraint is enabled or disabled. These properties are provided for compatibility with Oracle.
	// (Default: `true`) Specifies whether the constraint is enabled or disabled. These properties are provided for compatibility with Oracle.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// (Boolean) (Default: false) Whether the constraint is enforced
	// (Default: `false`) Whether the constraint is enforced
	Enforced *bool `json:"enforced,omitempty" tf:"enforced,omitempty"`

	// (Block List, Max: 1) Additional properties when type is set to foreign key. Not applicable for primary/unique keys (see below for nested schema)
	// Additional properties when type is set to foreign key. Not applicable for primary/unique keys
	ForeignKeyProperties []ForeignKeyPropertiesObservation `json:"foreignKeyProperties,omitempty" tf:"foreign_key_properties,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) (Default: DEFERRED) Whether the constraint is initially deferred or immediate
	// (Default: `DEFERRED`) Whether the constraint is initially deferred or immediate
	Initially *string `json:"initially,omitempty" tf:"initially,omitempty"`

	// (Boolean) (Default: true) Specifies whether a constraint in NOVALIDATE mode is taken into account during query rewrite.
	// (Default: `true`) Specifies whether a constraint in NOVALIDATE mode is taken into account during query rewrite.
	Rely *bool `json:"rely,omitempty" tf:"rely,omitempty"`

	// (String) Identifier for table to create constraint on. Format must follow: ""<db_name>"."<schema_name>"."<table_name>"" or "<db_name>.<schema_name>.<table_name>" (snowflake_table.my_table.id)
	// Identifier for table to create constraint on. Format must follow: "\"&lt;db_name&gt;\".\"&lt;schema_name&gt;\".\"&lt;table_name&gt;\"" or "&lt;db_name&gt;.&lt;schema_name&gt;.&lt;table_name&gt;" (snowflake_table.my_table.id)
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// (String) Type of constraint, one of 'UNIQUE', 'PRIMARY KEY', or 'FOREIGN KEY'
	// Type of constraint, one of 'UNIQUE', 'PRIMARY KEY', or 'FOREIGN KEY'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Boolean) (Default: false) Specifies whether to validate existing data on the table when a constraint is created. Only used in conjunction with the ENABLE property.
	// (Default: `false`) Specifies whether to validate existing data on the table when a constraint is created. Only used in conjunction with the ENABLE property.
	Validate *bool `json:"validate,omitempty" tf:"validate,omitempty"`
}

type ConstraintParameters struct {

	// (List of String) Columns to use in constraint key
	// Columns to use in constraint key
	// +kubebuilder:validation:Optional
	Columns []*string `json:"columns,omitempty" tf:"columns,omitempty"`

	// (String, Deprecated) Comment for the table constraint
	// Comment for the table constraint
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (Boolean) (Default: true) Whether the constraint is deferrable
	// (Default: `true`) Whether the constraint is deferrable
	// +kubebuilder:validation:Optional
	Deferrable *bool `json:"deferrable,omitempty" tf:"deferrable,omitempty"`

	// (Boolean) (Default: true) Specifies whether the constraint is enabled or disabled. These properties are provided for compatibility with Oracle.
	// (Default: `true`) Specifies whether the constraint is enabled or disabled. These properties are provided for compatibility with Oracle.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// (Boolean) (Default: false) Whether the constraint is enforced
	// (Default: `false`) Whether the constraint is enforced
	// +kubebuilder:validation:Optional
	Enforced *bool `json:"enforced,omitempty" tf:"enforced,omitempty"`

	// (Block List, Max: 1) Additional properties when type is set to foreign key. Not applicable for primary/unique keys (see below for nested schema)
	// Additional properties when type is set to foreign key. Not applicable for primary/unique keys
	// +kubebuilder:validation:Optional
	ForeignKeyProperties []ForeignKeyPropertiesParameters `json:"foreignKeyProperties,omitempty" tf:"foreign_key_properties,omitempty"`

	// (String) (Default: DEFERRED) Whether the constraint is initially deferred or immediate
	// (Default: `DEFERRED`) Whether the constraint is initially deferred or immediate
	// +kubebuilder:validation:Optional
	Initially *string `json:"initially,omitempty" tf:"initially,omitempty"`

	// (Boolean) (Default: true) Specifies whether a constraint in NOVALIDATE mode is taken into account during query rewrite.
	// (Default: `true`) Specifies whether a constraint in NOVALIDATE mode is taken into account during query rewrite.
	// +kubebuilder:validation:Optional
	Rely *bool `json:"rely,omitempty" tf:"rely,omitempty"`

	// (String) Identifier for table to create constraint on. Format must follow: ""<db_name>"."<schema_name>"."<table_name>"" or "<db_name>.<schema_name>.<table_name>" (snowflake_table.my_table.id)
	// Identifier for table to create constraint on. Format must follow: "\"&lt;db_name&gt;\".\"&lt;schema_name&gt;\".\"&lt;table_name&gt;\"" or "&lt;db_name&gt;.&lt;schema_name&gt;.&lt;table_name&gt;" (snowflake_table.my_table.id)
	// +kubebuilder:validation:Optional
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`

	// (String) Type of constraint, one of 'UNIQUE', 'PRIMARY KEY', or 'FOREIGN KEY'
	// Type of constraint, one of 'UNIQUE', 'PRIMARY KEY', or 'FOREIGN KEY'
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Boolean) (Default: false) Specifies whether to validate existing data on the table when a constraint is created. Only used in conjunction with the ENABLE property.
	// (Default: `false`) Specifies whether to validate existing data on the table when a constraint is created. Only used in conjunction with the ENABLE property.
	// +kubebuilder:validation:Optional
	Validate *bool `json:"validate,omitempty" tf:"validate,omitempty"`
}

type ForeignKeyPropertiesInitParameters struct {

	// (String) (Default: FULL) The match type for the foreign key. Not applicable for primary/unique keys
	// (Default: `FULL`) The match type for the foreign key. Not applicable for primary/unique keys
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// (String) (Default: NO ACTION) Specifies the action performed when the primary/unique key for the foreign key is deleted. Not applicable for primary/unique keys
	// (Default: `NO ACTION`) Specifies the action performed when the primary/unique key for the foreign key is deleted. Not applicable for primary/unique keys
	OnDelete *string `json:"onDelete,omitempty" tf:"on_delete,omitempty"`

	// (String) (Default: NO ACTION) Specifies the action performed when the primary/unique key for the foreign key is updated. Not applicable for primary/unique keys
	// (Default: `NO ACTION`) Specifies the action performed when the primary/unique key for the foreign key is updated. Not applicable for primary/unique keys
	OnUpdate *string `json:"onUpdate,omitempty" tf:"on_update,omitempty"`

	// (Block List, Min: 1, Max: 1) The table and columns that the foreign key references. (see below for nested schema)
	// The table and columns that the foreign key references.
	References []ReferencesInitParameters `json:"references,omitempty" tf:"references,omitempty"`
}

type ForeignKeyPropertiesObservation struct {

	// (String) (Default: FULL) The match type for the foreign key. Not applicable for primary/unique keys
	// (Default: `FULL`) The match type for the foreign key. Not applicable for primary/unique keys
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// (String) (Default: NO ACTION) Specifies the action performed when the primary/unique key for the foreign key is deleted. Not applicable for primary/unique keys
	// (Default: `NO ACTION`) Specifies the action performed when the primary/unique key for the foreign key is deleted. Not applicable for primary/unique keys
	OnDelete *string `json:"onDelete,omitempty" tf:"on_delete,omitempty"`

	// (String) (Default: NO ACTION) Specifies the action performed when the primary/unique key for the foreign key is updated. Not applicable for primary/unique keys
	// (Default: `NO ACTION`) Specifies the action performed when the primary/unique key for the foreign key is updated. Not applicable for primary/unique keys
	OnUpdate *string `json:"onUpdate,omitempty" tf:"on_update,omitempty"`

	// (Block List, Min: 1, Max: 1) The table and columns that the foreign key references. (see below for nested schema)
	// The table and columns that the foreign key references.
	References []ReferencesObservation `json:"references,omitempty" tf:"references,omitempty"`
}

type ForeignKeyPropertiesParameters struct {

	// (String) (Default: FULL) The match type for the foreign key. Not applicable for primary/unique keys
	// (Default: `FULL`) The match type for the foreign key. Not applicable for primary/unique keys
	// +kubebuilder:validation:Optional
	Match *string `json:"match,omitempty" tf:"match,omitempty"`

	// (String) (Default: NO ACTION) Specifies the action performed when the primary/unique key for the foreign key is deleted. Not applicable for primary/unique keys
	// (Default: `NO ACTION`) Specifies the action performed when the primary/unique key for the foreign key is deleted. Not applicable for primary/unique keys
	// +kubebuilder:validation:Optional
	OnDelete *string `json:"onDelete,omitempty" tf:"on_delete,omitempty"`

	// (String) (Default: NO ACTION) Specifies the action performed when the primary/unique key for the foreign key is updated. Not applicable for primary/unique keys
	// (Default: `NO ACTION`) Specifies the action performed when the primary/unique key for the foreign key is updated. Not applicable for primary/unique keys
	// +kubebuilder:validation:Optional
	OnUpdate *string `json:"onUpdate,omitempty" tf:"on_update,omitempty"`

	// (Block List, Min: 1, Max: 1) The table and columns that the foreign key references. (see below for nested schema)
	// The table and columns that the foreign key references.
	// +kubebuilder:validation:Optional
	References []ReferencesParameters `json:"references" tf:"references,omitempty"`
}

type ReferencesInitParameters struct {

	// (List of String) Columns to use in constraint key
	// Columns to use in foreign key reference
	Columns []*string `json:"columns,omitempty" tf:"columns,omitempty"`

	// (String) Identifier for table to create constraint on. Format must follow: ""<db_name>"."<schema_name>"."<table_name>"" or "<db_name>.<schema_name>.<table_name>" (snowflake_table.my_table.id)
	// Name of constraint
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`
}

type ReferencesObservation struct {

	// (List of String) Columns to use in constraint key
	// Columns to use in foreign key reference
	Columns []*string `json:"columns,omitempty" tf:"columns,omitempty"`

	// (String) Identifier for table to create constraint on. Format must follow: ""<db_name>"."<schema_name>"."<table_name>"" or "<db_name>.<schema_name>.<table_name>" (snowflake_table.my_table.id)
	// Name of constraint
	TableID *string `json:"tableId,omitempty" tf:"table_id,omitempty"`
}

type ReferencesParameters struct {

	// (List of String) Columns to use in constraint key
	// Columns to use in foreign key reference
	// +kubebuilder:validation:Optional
	Columns []*string `json:"columns" tf:"columns,omitempty"`

	// (String) Identifier for table to create constraint on. Format must follow: ""<db_name>"."<schema_name>"."<table_name>"" or "<db_name>.<schema_name>.<table_name>" (snowflake_table.my_table.id)
	// Name of constraint
	// +kubebuilder:validation:Optional
	TableID *string `json:"tableId" tf:"table_id,omitempty"`
}

// ConstraintSpec defines the desired state of Constraint
type ConstraintSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ConstraintParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ConstraintInitParameters `json:"initProvider,omitempty"`
}

// ConstraintStatus defines the observed state of Constraint.
type ConstraintStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ConstraintObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Constraint is the Schema for the Constraints API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Constraint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.columns) || (has(self.initProvider) && has(self.initProvider.columns))",message="spec.forProvider.columns is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tableId) || (has(self.initProvider) && has(self.initProvider.tableId))",message="spec.forProvider.tableId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ConstraintSpec   `json:"spec"`
	Status ConstraintStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ConstraintList contains a list of Constraints
type ConstraintList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Constraint `json:"items"`
}

// Repository type metadata.
var (
	Constraint_Kind             = "Constraint"
	Constraint_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Constraint_Kind}.String()
	Constraint_KindAPIVersion   = Constraint_Kind + "." + CRDGroupVersion.String()
	Constraint_GroupVersionKind = CRDGroupVersion.WithKind(Constraint_Kind)
)

func init() {
	SchemeBuilder.Register(&Constraint{}, &ConstraintList{})
}
