//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplication) DeepCopyInto(out *ColumnMaskingPolicyApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplication.
func (in *ColumnMaskingPolicyApplication) DeepCopy() *ColumnMaskingPolicyApplication {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ColumnMaskingPolicyApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplicationInitParameters) DeepCopyInto(out *ColumnMaskingPolicyApplicationInitParameters) {
	*out = *in
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = new(string)
		**out = **in
	}
	if in.MaskingPolicy != nil {
		in, out := &in.MaskingPolicy, &out.MaskingPolicy
		*out = new(string)
		**out = **in
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplicationInitParameters.
func (in *ColumnMaskingPolicyApplicationInitParameters) DeepCopy() *ColumnMaskingPolicyApplicationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplicationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplicationList) DeepCopyInto(out *ColumnMaskingPolicyApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ColumnMaskingPolicyApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplicationList.
func (in *ColumnMaskingPolicyApplicationList) DeepCopy() *ColumnMaskingPolicyApplicationList {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ColumnMaskingPolicyApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplicationObservation) DeepCopyInto(out *ColumnMaskingPolicyApplicationObservation) {
	*out = *in
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaskingPolicy != nil {
		in, out := &in.MaskingPolicy, &out.MaskingPolicy
		*out = new(string)
		**out = **in
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplicationObservation.
func (in *ColumnMaskingPolicyApplicationObservation) DeepCopy() *ColumnMaskingPolicyApplicationObservation {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplicationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplicationParameters) DeepCopyInto(out *ColumnMaskingPolicyApplicationParameters) {
	*out = *in
	if in.Column != nil {
		in, out := &in.Column, &out.Column
		*out = new(string)
		**out = **in
	}
	if in.MaskingPolicy != nil {
		in, out := &in.MaskingPolicy, &out.MaskingPolicy
		*out = new(string)
		**out = **in
	}
	if in.Table != nil {
		in, out := &in.Table, &out.Table
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplicationParameters.
func (in *ColumnMaskingPolicyApplicationParameters) DeepCopy() *ColumnMaskingPolicyApplicationParameters {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplicationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplicationSpec) DeepCopyInto(out *ColumnMaskingPolicyApplicationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplicationSpec.
func (in *ColumnMaskingPolicyApplicationSpec) DeepCopy() *ColumnMaskingPolicyApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColumnMaskingPolicyApplicationStatus) DeepCopyInto(out *ColumnMaskingPolicyApplicationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColumnMaskingPolicyApplicationStatus.
func (in *ColumnMaskingPolicyApplicationStatus) DeepCopy() *ColumnMaskingPolicyApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ColumnMaskingPolicyApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Constraint) DeepCopyInto(out *Constraint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Constraint.
func (in *Constraint) DeepCopy() *Constraint {
	if in == nil {
		return nil
	}
	out := new(Constraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Constraint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintInitParameters) DeepCopyInto(out *ConstraintInitParameters) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Deferrable != nil {
		in, out := &in.Deferrable, &out.Deferrable
		*out = new(bool)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Enforced != nil {
		in, out := &in.Enforced, &out.Enforced
		*out = new(bool)
		**out = **in
	}
	if in.ForeignKeyProperties != nil {
		in, out := &in.ForeignKeyProperties, &out.ForeignKeyProperties
		*out = make([]ForeignKeyPropertiesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Initially != nil {
		in, out := &in.Initially, &out.Initially
		*out = new(string)
		**out = **in
	}
	if in.Rely != nil {
		in, out := &in.Rely, &out.Rely
		*out = new(bool)
		**out = **in
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintInitParameters.
func (in *ConstraintInitParameters) DeepCopy() *ConstraintInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConstraintInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintList) DeepCopyInto(out *ConstraintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Constraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintList.
func (in *ConstraintList) DeepCopy() *ConstraintList {
	if in == nil {
		return nil
	}
	out := new(ConstraintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConstraintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintObservation) DeepCopyInto(out *ConstraintObservation) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Deferrable != nil {
		in, out := &in.Deferrable, &out.Deferrable
		*out = new(bool)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Enforced != nil {
		in, out := &in.Enforced, &out.Enforced
		*out = new(bool)
		**out = **in
	}
	if in.ForeignKeyProperties != nil {
		in, out := &in.ForeignKeyProperties, &out.ForeignKeyProperties
		*out = make([]ForeignKeyPropertiesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Initially != nil {
		in, out := &in.Initially, &out.Initially
		*out = new(string)
		**out = **in
	}
	if in.Rely != nil {
		in, out := &in.Rely, &out.Rely
		*out = new(bool)
		**out = **in
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintObservation.
func (in *ConstraintObservation) DeepCopy() *ConstraintObservation {
	if in == nil {
		return nil
	}
	out := new(ConstraintObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintParameters) DeepCopyInto(out *ConstraintParameters) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.Deferrable != nil {
		in, out := &in.Deferrable, &out.Deferrable
		*out = new(bool)
		**out = **in
	}
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
	if in.Enforced != nil {
		in, out := &in.Enforced, &out.Enforced
		*out = new(bool)
		**out = **in
	}
	if in.ForeignKeyProperties != nil {
		in, out := &in.ForeignKeyProperties, &out.ForeignKeyProperties
		*out = make([]ForeignKeyPropertiesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Initially != nil {
		in, out := &in.Initially, &out.Initially
		*out = new(string)
		**out = **in
	}
	if in.Rely != nil {
		in, out := &in.Rely, &out.Rely
		*out = new(bool)
		**out = **in
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintParameters.
func (in *ConstraintParameters) DeepCopy() *ConstraintParameters {
	if in == nil {
		return nil
	}
	out := new(ConstraintParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintSpec) DeepCopyInto(out *ConstraintSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintSpec.
func (in *ConstraintSpec) DeepCopy() *ConstraintSpec {
	if in == nil {
		return nil
	}
	out := new(ConstraintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintStatus) DeepCopyInto(out *ConstraintStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintStatus.
func (in *ConstraintStatus) DeepCopy() *ConstraintStatus {
	if in == nil {
		return nil
	}
	out := new(ConstraintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForeignKeyPropertiesInitParameters) DeepCopyInto(out *ForeignKeyPropertiesInitParameters) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.OnDelete != nil {
		in, out := &in.OnDelete, &out.OnDelete
		*out = new(string)
		**out = **in
	}
	if in.OnUpdate != nil {
		in, out := &in.OnUpdate, &out.OnUpdate
		*out = new(string)
		**out = **in
	}
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]ReferencesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForeignKeyPropertiesInitParameters.
func (in *ForeignKeyPropertiesInitParameters) DeepCopy() *ForeignKeyPropertiesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ForeignKeyPropertiesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForeignKeyPropertiesObservation) DeepCopyInto(out *ForeignKeyPropertiesObservation) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.OnDelete != nil {
		in, out := &in.OnDelete, &out.OnDelete
		*out = new(string)
		**out = **in
	}
	if in.OnUpdate != nil {
		in, out := &in.OnUpdate, &out.OnUpdate
		*out = new(string)
		**out = **in
	}
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]ReferencesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForeignKeyPropertiesObservation.
func (in *ForeignKeyPropertiesObservation) DeepCopy() *ForeignKeyPropertiesObservation {
	if in == nil {
		return nil
	}
	out := new(ForeignKeyPropertiesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForeignKeyPropertiesParameters) DeepCopyInto(out *ForeignKeyPropertiesParameters) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = new(string)
		**out = **in
	}
	if in.OnDelete != nil {
		in, out := &in.OnDelete, &out.OnDelete
		*out = new(string)
		**out = **in
	}
	if in.OnUpdate != nil {
		in, out := &in.OnUpdate, &out.OnUpdate
		*out = new(string)
		**out = **in
	}
	if in.References != nil {
		in, out := &in.References, &out.References
		*out = make([]ReferencesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForeignKeyPropertiesParameters.
func (in *ForeignKeyPropertiesParameters) DeepCopy() *ForeignKeyPropertiesParameters {
	if in == nil {
		return nil
	}
	out := new(ForeignKeyPropertiesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencesInitParameters) DeepCopyInto(out *ReferencesInitParameters) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencesInitParameters.
func (in *ReferencesInitParameters) DeepCopy() *ReferencesInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReferencesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencesObservation) DeepCopyInto(out *ReferencesObservation) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencesObservation.
func (in *ReferencesObservation) DeepCopy() *ReferencesObservation {
	if in == nil {
		return nil
	}
	out := new(ReferencesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencesParameters) DeepCopyInto(out *ReferencesParameters) {
	*out = *in
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TableID != nil {
		in, out := &in.TableID, &out.TableID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencesParameters.
func (in *ReferencesParameters) DeepCopy() *ReferencesParameters {
	if in == nil {
		return nil
	}
	out := new(ReferencesParameters)
	in.DeepCopyInto(out)
	return out
}
