apiVersion: managed.crossplane.io/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: managed/v1alpha1/account
  labels:
    testing.upbound.io/example-name: account
  name: account
spec:
  forProvider:
    adminName: admin
    adminPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    comment: A managed account.
    type: READER
