apiVersion: external.crossplane.io/v1alpha1
kind: Function
metadata:
  annotations:
    meta.upbound.io/example-id: external/v1alpha1/function
  labels:
    testing.upbound.io/example-name: test_ext_func
  name: test-ext-func
spec:
  forProvider:
    apiIntegration: api_integration_name
    arg:
    - name: arg1
      type: varchar
    - name: arg2
      type: varchar
    database: my_test_db
    returnBehavior: IMMUTABLE
    returnType: variant
    schema: my_test_schema
    urlOfProxyAndResource: https://123456.execute-api.us-west-2.amazonaws.com/prod/test_func
