apiVersion: account.crossplane.io/v1alpha1
kind: PasswordPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: account/v1alpha1/passwordpolicyattachment
  labels:
    testing.upbound.io/example-name: attachment
  name: attachment
spec:
  forProvider:
    passwordPolicy: ${snowflake_password_policy.default.fully_qualified_name}
