apiVersion: function.crossplane.io/v1alpha1
kind: SQL
metadata:
  annotations:
    meta.upbound.io/example-id: function/v1alpha1/sql
  labels:
    testing.upbound.io/example-name: minimal
  name: minimal
spec:
  forProvider:
    arguments:
    - argDataType: FLOAT
      argName: arg_name
    database: database_name
    functionDefinition: |
      arg_name
    returnType: FLOAT
    schema: schema_name
