// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyAttachmentInitParameters struct {

	// (String) Specifies the identifier for the network policy; must be unique for the account in which the network policy is created.
	// Specifies the identifier for the network policy; must be unique for the account in which the network policy is created.
	NetworkPolicyName *string `json:"networkPolicyName,omitempty" tf:"network_policy_name,omitempty"`

	// policy-per-account, it is the user's responsibility to enforce this. If multiple network policy resources have set_for_account: true, the final policy set on the account will be non-deterministic.<br><br>Additionally, a Snowflake account can only have one network policy set globally at any given time. This resource does not enforce one-policy-per-account, it is the user's responsibility to enforce this. If multiple network policy resources have `set_for_account: true`, the final policy set on the account will be non-deterministic.
	SetForAccount *bool `json:"setForAccount,omitempty" tf:"set_for_account,omitempty"`

	// (Set of String) Specifies which users the network policy should be attached to
	// Specifies which users the network policy should be attached to
	// +listType=set
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type PolicyAttachmentObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Specifies the identifier for the network policy; must be unique for the account in which the network policy is created.
	// Specifies the identifier for the network policy; must be unique for the account in which the network policy is created.
	NetworkPolicyName *string `json:"networkPolicyName,omitempty" tf:"network_policy_name,omitempty"`

	// policy-per-account, it is the user's responsibility to enforce this. If multiple network policy resources have set_for_account: true, the final policy set on the account will be non-deterministic.<br><br>Additionally, a Snowflake account can only have one network policy set globally at any given time. This resource does not enforce one-policy-per-account, it is the user's responsibility to enforce this. If multiple network policy resources have `set_for_account: true`, the final policy set on the account will be non-deterministic.
	SetForAccount *bool `json:"setForAccount,omitempty" tf:"set_for_account,omitempty"`

	// (Set of String) Specifies which users the network policy should be attached to
	// Specifies which users the network policy should be attached to
	// +listType=set
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type PolicyAttachmentParameters struct {

	// (String) Specifies the identifier for the network policy; must be unique for the account in which the network policy is created.
	// Specifies the identifier for the network policy; must be unique for the account in which the network policy is created.
	// +kubebuilder:validation:Optional
	NetworkPolicyName *string `json:"networkPolicyName,omitempty" tf:"network_policy_name,omitempty"`

	// policy-per-account, it is the user's responsibility to enforce this. If multiple network policy resources have set_for_account: true, the final policy set on the account will be non-deterministic.<br><br>Additionally, a Snowflake account can only have one network policy set globally at any given time. This resource does not enforce one-policy-per-account, it is the user's responsibility to enforce this. If multiple network policy resources have `set_for_account: true`, the final policy set on the account will be non-deterministic.
	// +kubebuilder:validation:Optional
	SetForAccount *bool `json:"setForAccount,omitempty" tf:"set_for_account,omitempty"`

	// (Set of String) Specifies which users the network policy should be attached to
	// Specifies which users the network policy should be attached to
	// +kubebuilder:validation:Optional
	// +listType=set
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

// PolicyAttachmentSpec defines the desired state of PolicyAttachment
type PolicyAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyAttachmentInitParameters `json:"initProvider,omitempty"`
}

// PolicyAttachmentStatus defines the observed state of PolicyAttachment.
type PolicyAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyAttachment is the Schema for the PolicyAttachments API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type PolicyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkPolicyName) || (has(self.initProvider) && has(self.initProvider.networkPolicyName))",message="spec.forProvider.networkPolicyName is a required parameter"
	Spec   PolicyAttachmentSpec   `json:"spec"`
	Status PolicyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyAttachmentList contains a list of PolicyAttachments
type PolicyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyAttachment `json:"items"`
}

// Repository type metadata.
var (
	PolicyAttachment_Kind             = "PolicyAttachment"
	PolicyAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyAttachment_Kind}.String()
	PolicyAttachment_KindAPIVersion   = PolicyAttachment_Kind + "." + CRDGroupVersion.String()
	PolicyAttachment_GroupVersionKind = CRDGroupVersion.WithKind(PolicyAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyAttachment{}, &PolicyAttachmentList{})
}
