//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRole) DeepCopyInto(out *DatabaseRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRole.
func (in *DatabaseRole) DeepCopy() *DatabaseRole {
	if in == nil {
		return nil
	}
	out := new(DatabaseRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleInitParameters) DeepCopyInto(out *DatabaseRoleInitParameters) {
	*out = *in
	if in.DatabaseRoleName != nil {
		in, out := &in.DatabaseRoleName, &out.DatabaseRoleName
		*out = new(string)
		**out = **in
	}
	if in.ParentDatabaseRoleName != nil {
		in, out := &in.ParentDatabaseRoleName, &out.ParentDatabaseRoleName
		*out = new(string)
		**out = **in
	}
	if in.ParentRoleName != nil {
		in, out := &in.ParentRoleName, &out.ParentRoleName
		*out = new(string)
		**out = **in
	}
	if in.ShareName != nil {
		in, out := &in.ShareName, &out.ShareName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleInitParameters.
func (in *DatabaseRoleInitParameters) DeepCopy() *DatabaseRoleInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleList) DeepCopyInto(out *DatabaseRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DatabaseRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleList.
func (in *DatabaseRoleList) DeepCopy() *DatabaseRoleList {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatabaseRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleObservation) DeepCopyInto(out *DatabaseRoleObservation) {
	*out = *in
	if in.DatabaseRoleName != nil {
		in, out := &in.DatabaseRoleName, &out.DatabaseRoleName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ParentDatabaseRoleName != nil {
		in, out := &in.ParentDatabaseRoleName, &out.ParentDatabaseRoleName
		*out = new(string)
		**out = **in
	}
	if in.ParentRoleName != nil {
		in, out := &in.ParentRoleName, &out.ParentRoleName
		*out = new(string)
		**out = **in
	}
	if in.ShareName != nil {
		in, out := &in.ShareName, &out.ShareName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleObservation.
func (in *DatabaseRoleObservation) DeepCopy() *DatabaseRoleObservation {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleParameters) DeepCopyInto(out *DatabaseRoleParameters) {
	*out = *in
	if in.DatabaseRoleName != nil {
		in, out := &in.DatabaseRoleName, &out.DatabaseRoleName
		*out = new(string)
		**out = **in
	}
	if in.ParentDatabaseRoleName != nil {
		in, out := &in.ParentDatabaseRoleName, &out.ParentDatabaseRoleName
		*out = new(string)
		**out = **in
	}
	if in.ParentRoleName != nil {
		in, out := &in.ParentRoleName, &out.ParentRoleName
		*out = new(string)
		**out = **in
	}
	if in.ShareName != nil {
		in, out := &in.ShareName, &out.ShareName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleParameters.
func (in *DatabaseRoleParameters) DeepCopy() *DatabaseRoleParameters {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleSpec) DeepCopyInto(out *DatabaseRoleSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleSpec.
func (in *DatabaseRoleSpec) DeepCopy() *DatabaseRoleSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseRoleStatus) DeepCopyInto(out *DatabaseRoleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseRoleStatus.
func (in *DatabaseRoleStatus) DeepCopy() *DatabaseRoleStatus {
	if in == nil {
		return nil
	}
	out := new(DatabaseRoleStatus)
	in.DeepCopyInto(out)
	return out
}
