// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AccountInitParameters struct {

	// (String) Identifier, as well as login name, for the initial user in the managed account. This user serves as the account administrator for the account.
	// Identifier, as well as login name, for the initial user in the managed account. This user serves as the account administrator for the account.
	AdminName *string `json:"adminName,omitempty" tf:"admin_name,omitempty"`

	// provided password policy.
	// Password for the initial user in the managed account. Check [Snowflake-provided password policy](https://docs.snowflake.com/en/user-guide/admin-user-management#snowflake-provided-password-policy).
	AdminPasswordSecretRef v1.SecretKeySelector `json:"adminPasswordSecretRef" tf:"-"`

	// (String) Specifies a comment for the managed account.
	// Specifies a comment for the managed account.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) (Default: READER) Specifies the type of managed account.
	// (Default: `READER`) Specifies the type of managed account.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AccountObservation struct {

	// (String) Identifier, as well as login name, for the initial user in the managed account. This user serves as the account administrator for the account.
	// Identifier, as well as login name, for the initial user in the managed account. This user serves as the account administrator for the account.
	AdminName *string `json:"adminName,omitempty" tf:"admin_name,omitempty"`

	// (String) Cloud in which the managed account is located.
	// Cloud in which the managed account is located.
	Cloud *string `json:"cloud,omitempty" tf:"cloud,omitempty"`

	// (String) Specifies a comment for the managed account.
	// Specifies a comment for the managed account.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) Date and time when the managed account was created.
	// Date and time when the managed account was created.
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Display name of the managed account.
	// Display name of the managed account.
	Locator *string `json:"locator,omitempty" tf:"locator,omitempty"`

	// (String) Snowflake Region in which the managed account is located.
	// Snowflake Region in which the managed account is located.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) (Default: READER) Specifies the type of managed account.
	// (Default: `READER`) Specifies the type of managed account.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (String) URL for accessing the managed account, particularly through the web interface.
	// URL for accessing the managed account, particularly through the web interface.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type AccountParameters struct {

	// (String) Identifier, as well as login name, for the initial user in the managed account. This user serves as the account administrator for the account.
	// Identifier, as well as login name, for the initial user in the managed account. This user serves as the account administrator for the account.
	// +kubebuilder:validation:Optional
	AdminName *string `json:"adminName,omitempty" tf:"admin_name,omitempty"`

	// provided password policy.
	// Password for the initial user in the managed account. Check [Snowflake-provided password policy](https://docs.snowflake.com/en/user-guide/admin-user-management#snowflake-provided-password-policy).
	// +kubebuilder:validation:Optional
	AdminPasswordSecretRef v1.SecretKeySelector `json:"adminPasswordSecretRef" tf:"-"`

	// (String) Specifies a comment for the managed account.
	// Specifies a comment for the managed account.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// (String) (Default: READER) Specifies the type of managed account.
	// (Default: `READER`) Specifies the type of managed account.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// AccountSpec defines the desired state of Account
type AccountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountInitParameters `json:"initProvider,omitempty"`
}

// AccountStatus defines the observed state of Account.
type AccountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Account is the Schema for the Accounts API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Account struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.adminName) || (has(self.initProvider) && has(self.initProvider.adminName))",message="spec.forProvider.adminName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.adminPasswordSecretRef)",message="spec.forProvider.adminPasswordSecretRef is a required parameter"
	Spec   AccountSpec   `json:"spec"`
	Status AccountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountList contains a list of Accounts
type AccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Account `json:"items"`
}

// Repository type metadata.
var (
	Account_Kind             = "Account"
	Account_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Account_Kind}.String()
	Account_KindAPIVersion   = Account_Kind + "." + CRDGroupVersion.String()
	Account_GroupVersionKind = CRDGroupVersion.WithKind(Account_Kind)
)

func init() {
	SchemeBuilder.Register(&Account{}, &AccountList{})
}
