apiVersion: user.crossplane.io/v1alpha1
kind: PasswordPolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/passwordpolicyattachment
  labels:
    testing.upbound.io/example-name: ppa
  name: ppa
spec:
  forProvider:
    passwordPolicyName: ${snowflake_password_policy.pp.fully_qualified_name}
    userName: Snowflake User - minimal

---

apiVersion: snowflakeuser.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/passwordpolicyattachment
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider:
    name: USER_NAME
