apiVersion: snowflakefileformat.crossplane.io/v1alpha1
kind: Format
metadata:
  annotations:
    meta.upbound.io/example-id: snowflakefileformat/v1alpha1/format
  labels:
    testing.upbound.io/example-name: example_file_format
  name: example-file-format2
spec:
  forProvider:
    database: MBB
    formatType: CSV
    name: EXAMPLE_FILE_FORMAT
    schema: PUBLIC
