apiVersion: api.crossplane.io/v1alpha1
kind: Integration
metadata:
  annotations:
    meta.upbound.io/example-id: api/v1alpha1/integration
  labels:
    testing.upbound.io/example-name: aws
  name: aws
spec:
  forProvider:
    apiAllowedPrefixes:
    - https://123456.execute-api.us-west-2.amazonaws.com/prod/
    apiAwsRoleArn: arn:aws:iam::000000000001:/role/test
    apiProvider: aws_api_gateway
    enabled: true
