apiVersion: snowflakeuser.crossplane.io/v1alpha1
kind: User
metadata:
  name: maxi
spec:
  forProvider:
    name: maxi3
    passwordSecretRef:
      key: password
      name: snowflake-creds
      namespace: crossplane-system    