// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DescribeOutputInitParameters struct {
}

type DescribeOutputObservation struct {

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	AutoResume *bool `json:"autoResume,omitempty" tf:"auto_resume,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	AutoSuspendSecs *float64 `json:"autoSuspendSecs,omitempty" tf:"auto_suspend_secs,omitempty"`

	// (String) Specifies a comment for the service.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see docs). Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	ComputePool *string `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Number)
	CurrentInstances *float64 `json:"currentInstances,omitempty" tf:"current_instances,omitempty"`

	// (String)
	DNSName *string `json:"dnsName,omitempty" tf:"dns_name,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Set of String) Specifies the names of the external access integrations that allow your service to access external sites.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Boolean)
	IsAsyncJob *bool `json:"isAsyncJob,omitempty" tf:"is_async_job,omitempty"`

	// (Boolean)
	IsJob *bool `json:"isJob,omitempty" tf:"is_job,omitempty"`

	// (Boolean)
	IsUpgrading *bool `json:"isUpgrading,omitempty" tf:"is_upgrading,omitempty"`

	// (String)
	ManagingObjectDomain *string `json:"managingObjectDomain,omitempty" tf:"managing_object_domain,omitempty"`

	// (String)
	ManagingObjectName *string `json:"managingObjectName,omitempty" tf:"managing_object_name,omitempty"`

	// (Number) Specifies the maximum number of service instances to run.
	MaxInstances *float64 `json:"maxInstances,omitempty" tf:"max_instances,omitempty"`

	// (Number) Specifies the minimum number of service instances to run.
	MinInstances *float64 `json:"minInstances,omitempty" tf:"min_instances,omitempty"`

	// (Number) Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	MinReadyInstances *float64 `json:"minReadyInstances,omitempty" tf:"min_ready_instances,omitempty"`

	// (String) Specifies the identifier for the service; must be unique for the schema in which the service is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String) Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	QueryWarehouse *string `json:"queryWarehouse,omitempty" tf:"query_warehouse,omitempty"`

	// (String)
	ResumedOn *string `json:"resumedOn,omitempty" tf:"resumed_on,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (String)
	Spec *string `json:"spec,omitempty" tf:"spec,omitempty"`

	// (String)
	SpecDigest *string `json:"specDigest,omitempty" tf:"spec_digest,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String)
	SuspendedOn *string `json:"suspendedOn,omitempty" tf:"suspended_on,omitempty"`

	// (Number)
	TargetInstances *float64 `json:"targetInstances,omitempty" tf:"target_instances,omitempty"`

	// (String)
	UpdatedOn *string `json:"updatedOn,omitempty" tf:"updated_on,omitempty"`
}

type DescribeOutputParameters struct {
}

type FromSpecificationInitParameters struct {

	// (String) The file name of the service specification. Example: spec.yaml.
	// The file name of the service specification. Example: `spec.yaml`.
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path to the service specification file on the given stage. When the path is specified, the / character is automatically added as a path prefix. Example: path/to/spec.
	// The path to the service specification file on the given stage. When the path is specified, the `/` character is automatically added as a path prefix. Example: `path/to/spec`.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The fully qualified name of the stage containing the service specification file. At symbol (@) is added automatically. Example: "\"<db_name>\".\"<schema_name>\".\"<stage_name>\"". For more information about this resource, see docs.
	// The fully qualified name of the stage containing the service specification file. At symbol (`@`) is added automatically. Example: `"\"<db_name>\".\"<schema_name>\".\"<stage_name>\""`. For more information about this resource, see [docs](./stage).
	Stage *string `json:"stage,omitempty" tf:"stage,omitempty"`

	// (String) The embedded text of the service specification.
	// The embedded text of the service specification.
	Text *string `json:"text,omitempty" tf:"text,omitempty"`
}

type FromSpecificationObservation struct {

	// (String) The file name of the service specification. Example: spec.yaml.
	// The file name of the service specification. Example: `spec.yaml`.
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path to the service specification file on the given stage. When the path is specified, the / character is automatically added as a path prefix. Example: path/to/spec.
	// The path to the service specification file on the given stage. When the path is specified, the `/` character is automatically added as a path prefix. Example: `path/to/spec`.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The fully qualified name of the stage containing the service specification file. At symbol (@) is added automatically. Example: "\"<db_name>\".\"<schema_name>\".\"<stage_name>\"". For more information about this resource, see docs.
	// The fully qualified name of the stage containing the service specification file. At symbol (`@`) is added automatically. Example: `"\"<db_name>\".\"<schema_name>\".\"<stage_name>\""`. For more information about this resource, see [docs](./stage).
	Stage *string `json:"stage,omitempty" tf:"stage,omitempty"`

	// (String) The embedded text of the service specification.
	// The embedded text of the service specification.
	Text *string `json:"text,omitempty" tf:"text,omitempty"`
}

type FromSpecificationParameters struct {

	// (String) The file name of the service specification. Example: spec.yaml.
	// The file name of the service specification. Example: `spec.yaml`.
	// +kubebuilder:validation:Optional
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path to the service specification file on the given stage. When the path is specified, the / character is automatically added as a path prefix. Example: path/to/spec.
	// The path to the service specification file on the given stage. When the path is specified, the `/` character is automatically added as a path prefix. Example: `path/to/spec`.
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The fully qualified name of the stage containing the service specification file. At symbol (@) is added automatically. Example: "\"<db_name>\".\"<schema_name>\".\"<stage_name>\"". For more information about this resource, see docs.
	// The fully qualified name of the stage containing the service specification file. At symbol (`@`) is added automatically. Example: `"\"<db_name>\".\"<schema_name>\".\"<stage_name>\""`. For more information about this resource, see [docs](./stage).
	// +kubebuilder:validation:Optional
	Stage *string `json:"stage,omitempty" tf:"stage,omitempty"`

	// (String) The embedded text of the service specification.
	// The embedded text of the service specification.
	// +kubebuilder:validation:Optional
	Text *string `json:"text,omitempty" tf:"text,omitempty"`
}

type FromSpecificationTemplateInitParameters struct {

	// (String) The file name of the service specification. Example: spec.yaml.
	// The file name of the service specification template. Example: `spec.yaml`.
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path to the service specification file on the given stage. When the path is specified, the / character is automatically added as a path prefix. Example: path/to/spec.
	// The path to the service specification template file on the given stage. When the path is specified, the `/` character is automatically added as a path prefix. Example: `path/to/spec`.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The fully qualified name of the stage containing the service specification file. At symbol (@) is added automatically. Example: "\"<db_name>\".\"<schema_name>\".\"<stage_name>\"". For more information about this resource, see docs.
	// The fully qualified name of the stage containing the service specification template file. At symbol (`@`) is added automatically. Example: `"\"<db_name>\".\"<schema_name>\".\"<stage_name>\""`. For more information about this resource, see [docs](./stage).
	Stage *string `json:"stage,omitempty" tf:"stage,omitempty"`

	// (String) The embedded text of the service specification.
	// The embedded text of the service specification template.
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// (Block List, Min: 1) List of the specified template variables and the values of those variables. (see below for nested schema)
	// List of the specified template variables and the values of those variables.
	Using []UsingInitParameters `json:"using,omitempty" tf:"using,omitempty"`
}

type FromSpecificationTemplateObservation struct {

	// (String) The file name of the service specification. Example: spec.yaml.
	// The file name of the service specification template. Example: `spec.yaml`.
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path to the service specification file on the given stage. When the path is specified, the / character is automatically added as a path prefix. Example: path/to/spec.
	// The path to the service specification template file on the given stage. When the path is specified, the `/` character is automatically added as a path prefix. Example: `path/to/spec`.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The fully qualified name of the stage containing the service specification file. At symbol (@) is added automatically. Example: "\"<db_name>\".\"<schema_name>\".\"<stage_name>\"". For more information about this resource, see docs.
	// The fully qualified name of the stage containing the service specification template file. At symbol (`@`) is added automatically. Example: `"\"<db_name>\".\"<schema_name>\".\"<stage_name>\""`. For more information about this resource, see [docs](./stage).
	Stage *string `json:"stage,omitempty" tf:"stage,omitempty"`

	// (String) The embedded text of the service specification.
	// The embedded text of the service specification template.
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// (Block List, Min: 1) List of the specified template variables and the values of those variables. (see below for nested schema)
	// List of the specified template variables and the values of those variables.
	Using []UsingObservation `json:"using,omitempty" tf:"using,omitempty"`
}

type FromSpecificationTemplateParameters struct {

	// (String) The file name of the service specification. Example: spec.yaml.
	// The file name of the service specification template. Example: `spec.yaml`.
	// +kubebuilder:validation:Optional
	File *string `json:"file,omitempty" tf:"file,omitempty"`

	// (String) The path to the service specification file on the given stage. When the path is specified, the / character is automatically added as a path prefix. Example: path/to/spec.
	// The path to the service specification template file on the given stage. When the path is specified, the `/` character is automatically added as a path prefix. Example: `path/to/spec`.
	// +kubebuilder:validation:Optional
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// (String) The fully qualified name of the stage containing the service specification file. At symbol (@) is added automatically. Example: "\"<db_name>\".\"<schema_name>\".\"<stage_name>\"". For more information about this resource, see docs.
	// The fully qualified name of the stage containing the service specification template file. At symbol (`@`) is added automatically. Example: `"\"<db_name>\".\"<schema_name>\".\"<stage_name>\""`. For more information about this resource, see [docs](./stage).
	// +kubebuilder:validation:Optional
	Stage *string `json:"stage,omitempty" tf:"stage,omitempty"`

	// (String) The embedded text of the service specification.
	// The embedded text of the service specification template.
	// +kubebuilder:validation:Optional
	Text *string `json:"text,omitempty" tf:"text,omitempty"`

	// (Block List, Min: 1) List of the specified template variables and the values of those variables. (see below for nested schema)
	// List of the specified template variables and the values of those variables.
	// +kubebuilder:validation:Optional
	Using []UsingParameters `json:"using" tf:"using,omitempty"`
}

type ServiceInitParameters struct {

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	AutoResume *string `json:"autoResume,omitempty" tf:"auto_resume,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	AutoSuspendSecs *float64 `json:"autoSuspendSecs,omitempty" tf:"auto_suspend_secs,omitempty"`

	// (String) Specifies a comment for the service.
	// Specifies a comment for the service.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see docs). Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// Specifies the name of the compute pool in your account on which to run the service. Identifiers with special or lower-case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see [docs](https://docs.snowflake.com/en/sql-reference/sql/create-compute-pool)). Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	ComputePool *string `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// (String) The database in which to create the service. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the service. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Set of String) Specifies the names of the external access integrations that allow your service to access external sites.
	// Specifies the names of the external access integrations that allow your service to access external sites.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Block List, Max: 1) Specifies the service specification to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See service specification for more information. (see below for nested schema)
	// Specifies the service specification to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See [service specification](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/specification-reference#general-guidelines) for more information.
	FromSpecification []FromSpecificationInitParameters `json:"fromSpecification,omitempty" tf:"from_specification,omitempty"`

	// (Block List, Max: 1) Specifies the service specification template to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See service specification for more information. (see below for nested schema)
	// Specifies the service specification template to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See [service specification](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/specification-reference#general-guidelines) for more information.
	FromSpecificationTemplate []FromSpecificationTemplateInitParameters `json:"fromSpecificationTemplate,omitempty" tf:"from_specification_template,omitempty"`

	// (Number) Specifies the maximum number of service instances to run.
	// Specifies the maximum number of service instances to run.
	MaxInstances *float64 `json:"maxInstances,omitempty" tf:"max_instances,omitempty"`

	// (Number) Specifies the minimum number of service instances to run.
	// Specifies the minimum number of service instances to run.
	MinInstances *float64 `json:"minInstances,omitempty" tf:"min_instances,omitempty"`

	// (Number) Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	// Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	MinReadyInstances *float64 `json:"minReadyInstances,omitempty" tf:"min_ready_instances,omitempty"`

	// (String) Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	QueryWarehouse *string `json:"queryWarehouse,omitempty" tf:"query_warehouse,omitempty"`

	// (String) The schema in which to create the service. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the service. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type ServiceObservation struct {

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	AutoResume *string `json:"autoResume,omitempty" tf:"auto_resume,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	AutoSuspendSecs *float64 `json:"autoSuspendSecs,omitempty" tf:"auto_suspend_secs,omitempty"`

	// (String) Specifies a comment for the service.
	// Specifies a comment for the service.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see docs). Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// Specifies the name of the compute pool in your account on which to run the service. Identifiers with special or lower-case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see [docs](https://docs.snowflake.com/en/sql-reference/sql/create-compute-pool)). Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	ComputePool *string `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// (String) The database in which to create the service. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the service. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (List of Object) Outputs the result of DESCRIBE SERVICE for the given service. (see below for nested schema)
	// Outputs the result of `DESCRIBE SERVICE` for the given service.
	DescribeOutput []DescribeOutputObservation `json:"describeOutput,omitempty" tf:"describe_output,omitempty"`

	// (Set of String) Specifies the names of the external access integrations that allow your service to access external sites.
	// Specifies the names of the external access integrations that allow your service to access external sites.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Block List, Max: 1) Specifies the service specification to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See service specification for more information. (see below for nested schema)
	// Specifies the service specification to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See [service specification](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/specification-reference#general-guidelines) for more information.
	FromSpecification []FromSpecificationObservation `json:"fromSpecification,omitempty" tf:"from_specification,omitempty"`

	// (Block List, Max: 1) Specifies the service specification template to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See service specification for more information. (see below for nested schema)
	// Specifies the service specification template to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See [service specification](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/specification-reference#general-guidelines) for more information.
	FromSpecificationTemplate []FromSpecificationTemplateObservation `json:"fromSpecificationTemplate,omitempty" tf:"from_specification_template,omitempty"`

	// (String) Fully qualified name of the resource. For more information, see object name resolution.
	// Fully qualified name of the resource. For more information, see [object name resolution](https://docs.snowflake.com/en/sql-reference/name-resolution).
	FullyQualifiedName *string `json:"fullyQualifiedName,omitempty" tf:"fully_qualified_name,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Specifies the maximum number of service instances to run.
	// Specifies the maximum number of service instances to run.
	MaxInstances *float64 `json:"maxInstances,omitempty" tf:"max_instances,omitempty"`

	// (Number) Specifies the minimum number of service instances to run.
	// Specifies the minimum number of service instances to run.
	MinInstances *float64 `json:"minInstances,omitempty" tf:"min_instances,omitempty"`

	// (Number) Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	// Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	MinReadyInstances *float64 `json:"minReadyInstances,omitempty" tf:"min_ready_instances,omitempty"`

	// (String) Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	QueryWarehouse *string `json:"queryWarehouse,omitempty" tf:"query_warehouse,omitempty"`

	// (String) The schema in which to create the service. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the service. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// (String) Specifies a type for the service. This field is used for checking external changes and recreating the resources if needed.
	// Specifies a type for the service. This field is used for checking external changes and recreating the resources if needed.
	ServiceType *string `json:"serviceType,omitempty" tf:"service_type,omitempty"`

	// (List of Object) Outputs the result of SHOW SERVICES for the given service. (see below for nested schema)
	// Outputs the result of `SHOW SERVICES` for the given service.
	ShowOutput []ServiceShowOutputObservation `json:"showOutput,omitempty" tf:"show_output,omitempty"`
}

type ServiceParameters struct {

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`default`)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	// +kubebuilder:validation:Optional
	AutoResume *string `json:"autoResume,omitempty" tf:"auto_resume,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	// (Default: fallback to Snowflake default - uses special value that cannot be set in the configuration manually (`-1`)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	// +kubebuilder:validation:Optional
	AutoSuspendSecs *float64 `json:"autoSuspendSecs,omitempty" tf:"auto_suspend_secs,omitempty"`

	// (String) Specifies a comment for the service.
	// Specifies a comment for the service.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see docs). Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// Specifies the name of the compute pool in your account on which to run the service. Identifiers with special or lower-case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see [docs](https://docs.snowflake.com/en/sql-reference/sql/create-compute-pool)). Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	ComputePool *string `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// (String) The database in which to create the service. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The database in which to create the service. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Database *string `json:"database,omitempty" tf:"database,omitempty"`

	// (Set of String) Specifies the names of the external access integrations that allow your service to access external sites.
	// Specifies the names of the external access integrations that allow your service to access external sites.
	// +kubebuilder:validation:Optional
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Block List, Max: 1) Specifies the service specification to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See service specification for more information. (see below for nested schema)
	// Specifies the service specification to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See [service specification](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/specification-reference#general-guidelines) for more information.
	// +kubebuilder:validation:Optional
	FromSpecification []FromSpecificationParameters `json:"fromSpecification,omitempty" tf:"from_specification,omitempty"`

	// (Block List, Max: 1) Specifies the service specification template to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See service specification for more information. (see below for nested schema)
	// Specifies the service specification template to use for the service. Note that external changes on this field and nested fields are not detected. Use correctly formatted YAML files. Watch out for the space/tabs indentation. See [service specification](https://docs.snowflake.com/en/developer-guide/snowpark-container-services/specification-reference#general-guidelines) for more information.
	// +kubebuilder:validation:Optional
	FromSpecificationTemplate []FromSpecificationTemplateParameters `json:"fromSpecificationTemplate,omitempty" tf:"from_specification_template,omitempty"`

	// (Number) Specifies the maximum number of service instances to run.
	// Specifies the maximum number of service instances to run.
	// +kubebuilder:validation:Optional
	MaxInstances *float64 `json:"maxInstances,omitempty" tf:"max_instances,omitempty"`

	// (Number) Specifies the minimum number of service instances to run.
	// Specifies the minimum number of service instances to run.
	// +kubebuilder:validation:Optional
	MinInstances *float64 `json:"minInstances,omitempty" tf:"min_instances,omitempty"`

	// (Number) Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	// Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	// +kubebuilder:validation:Optional
	MinReadyInstances *float64 `json:"minReadyInstances,omitempty" tf:"min_ready_instances,omitempty"`

	// (String) Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	QueryWarehouse *string `json:"queryWarehouse,omitempty" tf:"query_warehouse,omitempty"`

	// (String) The schema in which to create the service. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	// The schema in which to create the service. Due to technical limitations (read more [here](../guides/identifiers_rework_design_decisions#known-limitations-and-identifier-recommendations)), avoid using the following characters: `|`, `.`, `"`.
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`
}

type ServiceShowOutputInitParameters struct {
}

type ServiceShowOutputObservation struct {

	// uses special value that cannot be set in the configuration manually (default)) Specifies whether to automatically resume a service. Available options are: "true" or "false". When the value is not set in the configuration the provider will put "default" there which means to use the Snowflake default for this value.
	AutoResume *bool `json:"autoResume,omitempty" tf:"auto_resume,omitempty"`

	// uses special value that cannot be set in the configuration manually (-1)) Specifies the number of seconds of inactivity (service is idle) after which Snowflake automatically suspends the service.
	AutoSuspendSecs *float64 `json:"autoSuspendSecs,omitempty" tf:"auto_suspend_secs,omitempty"`

	// (String) Specifies a comment for the service.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// case characters are not supported. This limitation in the provider follows the limitation in Snowflake (see docs). Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	ComputePool *string `json:"computePool,omitempty" tf:"compute_pool,omitempty"`

	// (String)
	CreatedOn *string `json:"createdOn,omitempty" tf:"created_on,omitempty"`

	// (Number)
	CurrentInstances *float64 `json:"currentInstances,omitempty" tf:"current_instances,omitempty"`

	// (String)
	DNSName *string `json:"dnsName,omitempty" tf:"dns_name,omitempty"`

	// (String)
	DatabaseName *string `json:"databaseName,omitempty" tf:"database_name,omitempty"`

	// (Set of String) Specifies the names of the external access integrations that allow your service to access external sites.
	// +listType=set
	ExternalAccessIntegrations []*string `json:"externalAccessIntegrations,omitempty" tf:"external_access_integrations,omitempty"`

	// (Boolean)
	IsAsyncJob *bool `json:"isAsyncJob,omitempty" tf:"is_async_job,omitempty"`

	// (Boolean)
	IsJob *bool `json:"isJob,omitempty" tf:"is_job,omitempty"`

	// (Boolean)
	IsUpgrading *bool `json:"isUpgrading,omitempty" tf:"is_upgrading,omitempty"`

	// (String)
	ManagingObjectDomain *string `json:"managingObjectDomain,omitempty" tf:"managing_object_domain,omitempty"`

	// (String)
	ManagingObjectName *string `json:"managingObjectName,omitempty" tf:"managing_object_name,omitempty"`

	// (Number) Specifies the maximum number of service instances to run.
	MaxInstances *float64 `json:"maxInstances,omitempty" tf:"max_instances,omitempty"`

	// (Number) Specifies the minimum number of service instances to run.
	MinInstances *float64 `json:"minInstances,omitempty" tf:"min_instances,omitempty"`

	// (Number) Indicates the minimum service instances that must be ready for Snowflake to consider the service is ready to process requests.
	MinReadyInstances *float64 `json:"minReadyInstances,omitempty" tf:"min_ready_instances,omitempty"`

	// (String) Specifies the identifier for the service; must be unique for the schema in which the service is created. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// (String)
	OwnerRoleType *string `json:"ownerRoleType,omitempty" tf:"owner_role_type,omitempty"`

	// (String) Warehouse to use if a service container connects to Snowflake to execute a query but does not explicitly specify a warehouse to use. Due to technical limitations (read more here), avoid using the following characters: |, ., ".
	QueryWarehouse *string `json:"queryWarehouse,omitempty" tf:"query_warehouse,omitempty"`

	// (String)
	ResumedOn *string `json:"resumedOn,omitempty" tf:"resumed_on,omitempty"`

	// (String)
	SchemaName *string `json:"schemaName,omitempty" tf:"schema_name,omitempty"`

	// (String)
	SpecDigest *string `json:"specDigest,omitempty" tf:"spec_digest,omitempty"`

	// (String)
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String)
	SuspendedOn *string `json:"suspendedOn,omitempty" tf:"suspended_on,omitempty"`

	// (Number)
	TargetInstances *float64 `json:"targetInstances,omitempty" tf:"target_instances,omitempty"`

	// (String)
	UpdatedOn *string `json:"updatedOn,omitempty" tf:"updated_on,omitempty"`
}

type ServiceShowOutputParameters struct {
}

type UsingInitParameters struct {

	// (String) The name of the template variable. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the spec definition.
	// The name of the template variable. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the spec definition.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) The value to assign to the variable in the template. The provider wraps it in $$ by default, so be aware of that while referencing the argument in the spec definition. The value must either be alphanumeric or valid JSON.
	// The value to assign to the variable in the template. The provider wraps it in `$$` by default, so be aware of that while referencing the argument in the spec definition. The value must either be alphanumeric or valid JSON.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type UsingObservation struct {

	// (String) The name of the template variable. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the spec definition.
	// The name of the template variable. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the spec definition.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// (String) The value to assign to the variable in the template. The provider wraps it in $$ by default, so be aware of that while referencing the argument in the spec definition. The value must either be alphanumeric or valid JSON.
	// The value to assign to the variable in the template. The provider wraps it in `$$` by default, so be aware of that while referencing the argument in the spec definition. The value must either be alphanumeric or valid JSON.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type UsingParameters struct {

	// (String) The name of the template variable. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the spec definition.
	// The name of the template variable. The provider wraps it in double quotes by default, so be aware of that while referencing the argument in the spec definition.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// (String) The value to assign to the variable in the template. The provider wraps it in $$ by default, so be aware of that while referencing the argument in the spec definition. The value must either be alphanumeric or valid JSON.
	// The value to assign to the variable in the template. The provider wraps it in `$$` by default, so be aware of that while referencing the argument in the spec definition. The value must either be alphanumeric or valid JSON.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// ServiceSpec defines the desired state of Service
type ServiceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceInitParameters `json:"initProvider,omitempty"`
}

// ServiceStatus defines the observed state of Service.
type ServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Service is the Schema for the Services API. Resource used to manage services. For more information, check services documentation https://docs.snowflake.com/en/sql-reference/sql/create-service. A long-running service is like a web service that does not end automatically. After you create a service, Snowflake manages the running service. For example, if a service container stops, for whatever reason, Snowflake restarts that container so the service runs uninterrupted. See Working with services https://docs.snowflake.com/en/developer-guide/snowpark-container-services/working-with-services developer guide for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,snowflake}
type Service struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.computePool) || (has(self.initProvider) && has(self.initProvider.computePool))",message="spec.forProvider.computePool is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.database) || (has(self.initProvider) && has(self.initProvider.database))",message="spec.forProvider.database is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.schema) || (has(self.initProvider) && has(self.initProvider.schema))",message="spec.forProvider.schema is a required parameter"
	Spec   ServiceSpec   `json:"spec"`
	Status ServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceList contains a list of Services
type ServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Service `json:"items"`
}

// Repository type metadata.
var (
	Service_Kind             = "Service"
	Service_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Service_Kind}.String()
	Service_KindAPIVersion   = Service_Kind + "." + CRDGroupVersion.String()
	Service_GroupVersionKind = CRDGroupVersion.WithKind(Service_Kind)
)

func init() {
	SchemeBuilder.Register(&Service{}, &ServiceList{})
}
