apiVersion: dynamic.crossplane.io/v1alpha1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: dynamic/v1alpha1/table
  labels:
    testing.upbound.io/example-name: dt
  name: dt
spec:
  forProvider:
    comment: example comment
    database: mydb
    query: SELECT product_id, product_name FROM "mydb"."myschema"."staging_table"
    schema: myschema
    targetLag:
    - maximumDuration: 20 minutes
    warehouse: mywh
